/*
World Anvil Public API Documentation

Welcome to the World Anvil Public API Documentation. This API provides developers and World Anvil users with programmatic access to the extensive features of the World Anvil worldbuilding platform. Whether you're building integrations, automating tasks, or creating custom experiences, this API empowers you to interact with your worldbuilding data seamlessly.

API version: 2.0.0 - Boromir
Contact: contact@worldanvil.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package worldanvil

import (
	"encoding/json"
	"fmt"
)

// checks if the BlockCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockCreate{}

// BlockCreate struct for BlockCreate
type BlockCreate struct {
	Id *int32 `json:"id,omitempty"`
	Title string `json:"title"`
	Slug NullableString `json:"slug,omitempty"`
	State *string `json:"state,omitempty"`
	IsWip NullableString `json:"isWip,omitempty"`
	IsDraft NullableString `json:"isDraft,omitempty"`
	EntityClass *string `json:"entityClass,omitempty"`
	Icon *string `json:"icon,omitempty"`
	Url *string `json:"url,omitempty"`
	Subscribergroups []string `json:"subscribergroups,omitempty"`
	FolderId NullableString `json:"folderId,omitempty"`
	Tags *string `json:"tags,omitempty"`
	UpdateDate *Object `json:"updateDate,omitempty"`
	IsEditable *bool `json:"isEditable,omitempty"`
	Success *bool `json:"success,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
	DataParser *Yaml `json:"dataParser,omitempty"`
	Textualdata *string `json:"textualdata,omitempty"`
	Tabulardata NullableString `json:"tabulardata,omitempty"`
	Jsondata NullableString `json:"jsondata,omitempty"`
	IsShared *bool `json:"isShared,omitempty"`
	IsSRD *bool `json:"isSRD,omitempty"`
	Template ArticleGenericUpdateObjectPropertiesBlock `json:"template"`
	RPGSRD ArticleGenericUpdateObjectPropertiesBlock `json:"RPGSRD"`
	Author *ArticleGenericUpdateObjectPropertiesManuscriptsInner `json:"author,omitempty"`
	Folder *ArticleGenericUpdateObjectPropertiesBlock `json:"folder,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BlockCreate BlockCreate

// NewBlockCreate instantiates a new BlockCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockCreate(title string, template ArticleGenericUpdateObjectPropertiesBlock, rPGSRD ArticleGenericUpdateObjectPropertiesBlock) *BlockCreate {
	this := BlockCreate{}
	this.Title = title
	this.Template = template
	this.RPGSRD = rPGSRD
	return &this
}

// NewBlockCreateWithDefaults instantiates a new BlockCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockCreateWithDefaults() *BlockCreate {
	this := BlockCreate{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BlockCreate) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BlockCreate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *BlockCreate) SetId(v int32) {
	o.Id = &v
}

// GetTitle returns the Title field value
func (o *BlockCreate) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *BlockCreate) SetTitle(v string) {
	o.Title = v
}

// GetSlug returns the Slug field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlockCreate) GetSlug() string {
	if o == nil || IsNil(o.Slug.Get()) {
		var ret string
		return ret
	}
	return *o.Slug.Get()
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlockCreate) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slug.Get(), o.Slug.IsSet()
}

// HasSlug returns a boolean if a field has been set.
func (o *BlockCreate) HasSlug() bool {
	if o != nil && o.Slug.IsSet() {
		return true
	}

	return false
}

// SetSlug gets a reference to the given NullableString and assigns it to the Slug field.
func (o *BlockCreate) SetSlug(v string) {
	o.Slug.Set(&v)
}
// SetSlugNil sets the value for Slug to be an explicit nil
func (o *BlockCreate) SetSlugNil() {
	o.Slug.Set(nil)
}

// UnsetSlug ensures that no value is present for Slug, not even an explicit nil
func (o *BlockCreate) UnsetSlug() {
	o.Slug.Unset()
}

// GetState returns the State field value if set, zero value otherwise.
func (o *BlockCreate) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *BlockCreate) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *BlockCreate) SetState(v string) {
	o.State = &v
}

// GetIsWip returns the IsWip field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlockCreate) GetIsWip() string {
	if o == nil || IsNil(o.IsWip.Get()) {
		var ret string
		return ret
	}
	return *o.IsWip.Get()
}

// GetIsWipOk returns a tuple with the IsWip field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlockCreate) GetIsWipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsWip.Get(), o.IsWip.IsSet()
}

// HasIsWip returns a boolean if a field has been set.
func (o *BlockCreate) HasIsWip() bool {
	if o != nil && o.IsWip.IsSet() {
		return true
	}

	return false
}

// SetIsWip gets a reference to the given NullableString and assigns it to the IsWip field.
func (o *BlockCreate) SetIsWip(v string) {
	o.IsWip.Set(&v)
}
// SetIsWipNil sets the value for IsWip to be an explicit nil
func (o *BlockCreate) SetIsWipNil() {
	o.IsWip.Set(nil)
}

// UnsetIsWip ensures that no value is present for IsWip, not even an explicit nil
func (o *BlockCreate) UnsetIsWip() {
	o.IsWip.Unset()
}

// GetIsDraft returns the IsDraft field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlockCreate) GetIsDraft() string {
	if o == nil || IsNil(o.IsDraft.Get()) {
		var ret string
		return ret
	}
	return *o.IsDraft.Get()
}

// GetIsDraftOk returns a tuple with the IsDraft field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlockCreate) GetIsDraftOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsDraft.Get(), o.IsDraft.IsSet()
}

// HasIsDraft returns a boolean if a field has been set.
func (o *BlockCreate) HasIsDraft() bool {
	if o != nil && o.IsDraft.IsSet() {
		return true
	}

	return false
}

// SetIsDraft gets a reference to the given NullableString and assigns it to the IsDraft field.
func (o *BlockCreate) SetIsDraft(v string) {
	o.IsDraft.Set(&v)
}
// SetIsDraftNil sets the value for IsDraft to be an explicit nil
func (o *BlockCreate) SetIsDraftNil() {
	o.IsDraft.Set(nil)
}

// UnsetIsDraft ensures that no value is present for IsDraft, not even an explicit nil
func (o *BlockCreate) UnsetIsDraft() {
	o.IsDraft.Unset()
}

// GetEntityClass returns the EntityClass field value if set, zero value otherwise.
func (o *BlockCreate) GetEntityClass() string {
	if o == nil || IsNil(o.EntityClass) {
		var ret string
		return ret
	}
	return *o.EntityClass
}

// GetEntityClassOk returns a tuple with the EntityClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetEntityClassOk() (*string, bool) {
	if o == nil || IsNil(o.EntityClass) {
		return nil, false
	}
	return o.EntityClass, true
}

// HasEntityClass returns a boolean if a field has been set.
func (o *BlockCreate) HasEntityClass() bool {
	if o != nil && !IsNil(o.EntityClass) {
		return true
	}

	return false
}

// SetEntityClass gets a reference to the given string and assigns it to the EntityClass field.
func (o *BlockCreate) SetEntityClass(v string) {
	o.EntityClass = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *BlockCreate) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *BlockCreate) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *BlockCreate) SetIcon(v string) {
	o.Icon = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BlockCreate) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BlockCreate) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BlockCreate) SetUrl(v string) {
	o.Url = &v
}

// GetSubscribergroups returns the Subscribergroups field value if set, zero value otherwise.
func (o *BlockCreate) GetSubscribergroups() []string {
	if o == nil || IsNil(o.Subscribergroups) {
		var ret []string
		return ret
	}
	return o.Subscribergroups
}

// GetSubscribergroupsOk returns a tuple with the Subscribergroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetSubscribergroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.Subscribergroups) {
		return nil, false
	}
	return o.Subscribergroups, true
}

// HasSubscribergroups returns a boolean if a field has been set.
func (o *BlockCreate) HasSubscribergroups() bool {
	if o != nil && !IsNil(o.Subscribergroups) {
		return true
	}

	return false
}

// SetSubscribergroups gets a reference to the given []string and assigns it to the Subscribergroups field.
func (o *BlockCreate) SetSubscribergroups(v []string) {
	o.Subscribergroups = v
}

// GetFolderId returns the FolderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlockCreate) GetFolderId() string {
	if o == nil || IsNil(o.FolderId.Get()) {
		var ret string
		return ret
	}
	return *o.FolderId.Get()
}

// GetFolderIdOk returns a tuple with the FolderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlockCreate) GetFolderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FolderId.Get(), o.FolderId.IsSet()
}

// HasFolderId returns a boolean if a field has been set.
func (o *BlockCreate) HasFolderId() bool {
	if o != nil && o.FolderId.IsSet() {
		return true
	}

	return false
}

// SetFolderId gets a reference to the given NullableString and assigns it to the FolderId field.
func (o *BlockCreate) SetFolderId(v string) {
	o.FolderId.Set(&v)
}
// SetFolderIdNil sets the value for FolderId to be an explicit nil
func (o *BlockCreate) SetFolderIdNil() {
	o.FolderId.Set(nil)
}

// UnsetFolderId ensures that no value is present for FolderId, not even an explicit nil
func (o *BlockCreate) UnsetFolderId() {
	o.FolderId.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *BlockCreate) GetTags() string {
	if o == nil || IsNil(o.Tags) {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetTagsOk() (*string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *BlockCreate) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *BlockCreate) SetTags(v string) {
	o.Tags = &v
}

// GetUpdateDate returns the UpdateDate field value if set, zero value otherwise.
func (o *BlockCreate) GetUpdateDate() Object {
	if o == nil || IsNil(o.UpdateDate) {
		var ret Object
		return ret
	}
	return *o.UpdateDate
}

// GetUpdateDateOk returns a tuple with the UpdateDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetUpdateDateOk() (*Object, bool) {
	if o == nil || IsNil(o.UpdateDate) {
		return nil, false
	}
	return o.UpdateDate, true
}

// HasUpdateDate returns a boolean if a field has been set.
func (o *BlockCreate) HasUpdateDate() bool {
	if o != nil && !IsNil(o.UpdateDate) {
		return true
	}

	return false
}

// SetUpdateDate gets a reference to the given Object and assigns it to the UpdateDate field.
func (o *BlockCreate) SetUpdateDate(v Object) {
	o.UpdateDate = &v
}

// GetIsEditable returns the IsEditable field value if set, zero value otherwise.
func (o *BlockCreate) GetIsEditable() bool {
	if o == nil || IsNil(o.IsEditable) {
		var ret bool
		return ret
	}
	return *o.IsEditable
}

// GetIsEditableOk returns a tuple with the IsEditable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetIsEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEditable) {
		return nil, false
	}
	return o.IsEditable, true
}

// HasIsEditable returns a boolean if a field has been set.
func (o *BlockCreate) HasIsEditable() bool {
	if o != nil && !IsNil(o.IsEditable) {
		return true
	}

	return false
}

// SetIsEditable gets a reference to the given bool and assigns it to the IsEditable field.
func (o *BlockCreate) SetIsEditable(v bool) {
	o.IsEditable = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *BlockCreate) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *BlockCreate) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *BlockCreate) SetSuccess(v bool) {
	o.Success = &v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *BlockCreate) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *BlockCreate) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *BlockCreate) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetDataParser returns the DataParser field value if set, zero value otherwise.
func (o *BlockCreate) GetDataParser() Yaml {
	if o == nil || IsNil(o.DataParser) {
		var ret Yaml
		return ret
	}
	return *o.DataParser
}

// GetDataParserOk returns a tuple with the DataParser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetDataParserOk() (*Yaml, bool) {
	if o == nil || IsNil(o.DataParser) {
		return nil, false
	}
	return o.DataParser, true
}

// HasDataParser returns a boolean if a field has been set.
func (o *BlockCreate) HasDataParser() bool {
	if o != nil && !IsNil(o.DataParser) {
		return true
	}

	return false
}

// SetDataParser gets a reference to the given Yaml and assigns it to the DataParser field.
func (o *BlockCreate) SetDataParser(v Yaml) {
	o.DataParser = &v
}

// GetTextualdata returns the Textualdata field value if set, zero value otherwise.
func (o *BlockCreate) GetTextualdata() string {
	if o == nil || IsNil(o.Textualdata) {
		var ret string
		return ret
	}
	return *o.Textualdata
}

// GetTextualdataOk returns a tuple with the Textualdata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetTextualdataOk() (*string, bool) {
	if o == nil || IsNil(o.Textualdata) {
		return nil, false
	}
	return o.Textualdata, true
}

// HasTextualdata returns a boolean if a field has been set.
func (o *BlockCreate) HasTextualdata() bool {
	if o != nil && !IsNil(o.Textualdata) {
		return true
	}

	return false
}

// SetTextualdata gets a reference to the given string and assigns it to the Textualdata field.
func (o *BlockCreate) SetTextualdata(v string) {
	o.Textualdata = &v
}

// GetTabulardata returns the Tabulardata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlockCreate) GetTabulardata() string {
	if o == nil || IsNil(o.Tabulardata.Get()) {
		var ret string
		return ret
	}
	return *o.Tabulardata.Get()
}

// GetTabulardataOk returns a tuple with the Tabulardata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlockCreate) GetTabulardataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tabulardata.Get(), o.Tabulardata.IsSet()
}

// HasTabulardata returns a boolean if a field has been set.
func (o *BlockCreate) HasTabulardata() bool {
	if o != nil && o.Tabulardata.IsSet() {
		return true
	}

	return false
}

// SetTabulardata gets a reference to the given NullableString and assigns it to the Tabulardata field.
func (o *BlockCreate) SetTabulardata(v string) {
	o.Tabulardata.Set(&v)
}
// SetTabulardataNil sets the value for Tabulardata to be an explicit nil
func (o *BlockCreate) SetTabulardataNil() {
	o.Tabulardata.Set(nil)
}

// UnsetTabulardata ensures that no value is present for Tabulardata, not even an explicit nil
func (o *BlockCreate) UnsetTabulardata() {
	o.Tabulardata.Unset()
}

// GetJsondata returns the Jsondata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlockCreate) GetJsondata() string {
	if o == nil || IsNil(o.Jsondata.Get()) {
		var ret string
		return ret
	}
	return *o.Jsondata.Get()
}

// GetJsondataOk returns a tuple with the Jsondata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlockCreate) GetJsondataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jsondata.Get(), o.Jsondata.IsSet()
}

// HasJsondata returns a boolean if a field has been set.
func (o *BlockCreate) HasJsondata() bool {
	if o != nil && o.Jsondata.IsSet() {
		return true
	}

	return false
}

// SetJsondata gets a reference to the given NullableString and assigns it to the Jsondata field.
func (o *BlockCreate) SetJsondata(v string) {
	o.Jsondata.Set(&v)
}
// SetJsondataNil sets the value for Jsondata to be an explicit nil
func (o *BlockCreate) SetJsondataNil() {
	o.Jsondata.Set(nil)
}

// UnsetJsondata ensures that no value is present for Jsondata, not even an explicit nil
func (o *BlockCreate) UnsetJsondata() {
	o.Jsondata.Unset()
}

// GetIsShared returns the IsShared field value if set, zero value otherwise.
func (o *BlockCreate) GetIsShared() bool {
	if o == nil || IsNil(o.IsShared) {
		var ret bool
		return ret
	}
	return *o.IsShared
}

// GetIsSharedOk returns a tuple with the IsShared field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetIsSharedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsShared) {
		return nil, false
	}
	return o.IsShared, true
}

// HasIsShared returns a boolean if a field has been set.
func (o *BlockCreate) HasIsShared() bool {
	if o != nil && !IsNil(o.IsShared) {
		return true
	}

	return false
}

// SetIsShared gets a reference to the given bool and assigns it to the IsShared field.
func (o *BlockCreate) SetIsShared(v bool) {
	o.IsShared = &v
}

// GetIsSRD returns the IsSRD field value if set, zero value otherwise.
func (o *BlockCreate) GetIsSRD() bool {
	if o == nil || IsNil(o.IsSRD) {
		var ret bool
		return ret
	}
	return *o.IsSRD
}

// GetIsSRDOk returns a tuple with the IsSRD field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetIsSRDOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSRD) {
		return nil, false
	}
	return o.IsSRD, true
}

// HasIsSRD returns a boolean if a field has been set.
func (o *BlockCreate) HasIsSRD() bool {
	if o != nil && !IsNil(o.IsSRD) {
		return true
	}

	return false
}

// SetIsSRD gets a reference to the given bool and assigns it to the IsSRD field.
func (o *BlockCreate) SetIsSRD(v bool) {
	o.IsSRD = &v
}

// GetTemplate returns the Template field value
func (o *BlockCreate) GetTemplate() ArticleGenericUpdateObjectPropertiesBlock {
	if o == nil {
		var ret ArticleGenericUpdateObjectPropertiesBlock
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetTemplateOk() (*ArticleGenericUpdateObjectPropertiesBlock, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *BlockCreate) SetTemplate(v ArticleGenericUpdateObjectPropertiesBlock) {
	o.Template = v
}

// GetRPGSRD returns the RPGSRD field value
func (o *BlockCreate) GetRPGSRD() ArticleGenericUpdateObjectPropertiesBlock {
	if o == nil {
		var ret ArticleGenericUpdateObjectPropertiesBlock
		return ret
	}

	return o.RPGSRD
}

// GetRPGSRDOk returns a tuple with the RPGSRD field value
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetRPGSRDOk() (*ArticleGenericUpdateObjectPropertiesBlock, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RPGSRD, true
}

// SetRPGSRD sets field value
func (o *BlockCreate) SetRPGSRD(v ArticleGenericUpdateObjectPropertiesBlock) {
	o.RPGSRD = v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *BlockCreate) GetAuthor() ArticleGenericUpdateObjectPropertiesManuscriptsInner {
	if o == nil || IsNil(o.Author) {
		var ret ArticleGenericUpdateObjectPropertiesManuscriptsInner
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetAuthorOk() (*ArticleGenericUpdateObjectPropertiesManuscriptsInner, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *BlockCreate) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given ArticleGenericUpdateObjectPropertiesManuscriptsInner and assigns it to the Author field.
func (o *BlockCreate) SetAuthor(v ArticleGenericUpdateObjectPropertiesManuscriptsInner) {
	o.Author = &v
}

// GetFolder returns the Folder field value if set, zero value otherwise.
func (o *BlockCreate) GetFolder() ArticleGenericUpdateObjectPropertiesBlock {
	if o == nil || IsNil(o.Folder) {
		var ret ArticleGenericUpdateObjectPropertiesBlock
		return ret
	}
	return *o.Folder
}

// GetFolderOk returns a tuple with the Folder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockCreate) GetFolderOk() (*ArticleGenericUpdateObjectPropertiesBlock, bool) {
	if o == nil || IsNil(o.Folder) {
		return nil, false
	}
	return o.Folder, true
}

// HasFolder returns a boolean if a field has been set.
func (o *BlockCreate) HasFolder() bool {
	if o != nil && !IsNil(o.Folder) {
		return true
	}

	return false
}

// SetFolder gets a reference to the given ArticleGenericUpdateObjectPropertiesBlock and assigns it to the Folder field.
func (o *BlockCreate) SetFolder(v ArticleGenericUpdateObjectPropertiesBlock) {
	o.Folder = &v
}

func (o BlockCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["title"] = o.Title
	if o.Slug.IsSet() {
		toSerialize["slug"] = o.Slug.Get()
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if o.IsWip.IsSet() {
		toSerialize["isWip"] = o.IsWip.Get()
	}
	if o.IsDraft.IsSet() {
		toSerialize["isDraft"] = o.IsDraft.Get()
	}
	if !IsNil(o.EntityClass) {
		toSerialize["entityClass"] = o.EntityClass
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Subscribergroups) {
		toSerialize["subscribergroups"] = o.Subscribergroups
	}
	if o.FolderId.IsSet() {
		toSerialize["folderId"] = o.FolderId.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.UpdateDate) {
		toSerialize["updateDate"] = o.UpdateDate
	}
	if !IsNil(o.IsEditable) {
		toSerialize["isEditable"] = o.IsEditable
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	if !IsNil(o.DataParser) {
		toSerialize["dataParser"] = o.DataParser
	}
	if !IsNil(o.Textualdata) {
		toSerialize["textualdata"] = o.Textualdata
	}
	if o.Tabulardata.IsSet() {
		toSerialize["tabulardata"] = o.Tabulardata.Get()
	}
	if o.Jsondata.IsSet() {
		toSerialize["jsondata"] = o.Jsondata.Get()
	}
	if !IsNil(o.IsShared) {
		toSerialize["isShared"] = o.IsShared
	}
	if !IsNil(o.IsSRD) {
		toSerialize["isSRD"] = o.IsSRD
	}
	toSerialize["template"] = o.Template
	toSerialize["RPGSRD"] = o.RPGSRD
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Folder) {
		toSerialize["folder"] = o.Folder
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BlockCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"template",
		"RPGSRD",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlockCreate := _BlockCreate{}

	err = json.Unmarshal(data, &varBlockCreate)

	if err != nil {
		return err
	}

	*o = BlockCreate(varBlockCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "title")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "state")
		delete(additionalProperties, "isWip")
		delete(additionalProperties, "isDraft")
		delete(additionalProperties, "entityClass")
		delete(additionalProperties, "icon")
		delete(additionalProperties, "url")
		delete(additionalProperties, "subscribergroups")
		delete(additionalProperties, "folderId")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "updateDate")
		delete(additionalProperties, "isEditable")
		delete(additionalProperties, "success")
		delete(additionalProperties, "identifier")
		delete(additionalProperties, "dataParser")
		delete(additionalProperties, "textualdata")
		delete(additionalProperties, "tabulardata")
		delete(additionalProperties, "jsondata")
		delete(additionalProperties, "isShared")
		delete(additionalProperties, "isSRD")
		delete(additionalProperties, "template")
		delete(additionalProperties, "RPGSRD")
		delete(additionalProperties, "author")
		delete(additionalProperties, "folder")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBlockCreate struct {
	value *BlockCreate
	isSet bool
}

func (v NullableBlockCreate) Get() *BlockCreate {
	return v.value
}

func (v *NullableBlockCreate) Set(val *BlockCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockCreate(val *BlockCreate) *NullableBlockCreate {
	return &NullableBlockCreate{value: val, isSet: true}
}

func (v NullableBlockCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


