/*
World Anvil Public API Documentation

Welcome to the World Anvil Public API Documentation. This API provides developers and World Anvil users with programmatic access to the extensive features of the World Anvil worldbuilding platform. Whether you're building integrations, automating tasks, or creating custom experiences, this API empowers you to interact with your worldbuilding data seamlessly.

API version: 2.0.0 - Boromir
Contact: contact@worldanvil.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package worldanvil

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ArticleGenericGR3AncestryThirdUp - struct for ArticleGenericGR3AncestryThirdUp
type ArticleGenericGR3AncestryThirdUp struct {
	ArticleRef *ArticleRef
	ERRORUNKNOWN *ERRORUNKNOWN
}

// ArticleRefAsArticleGenericGR3AncestryThirdUp is a convenience function that returns ArticleRef wrapped in ArticleGenericGR3AncestryThirdUp
func ArticleRefAsArticleGenericGR3AncestryThirdUp(v *ArticleRef) ArticleGenericGR3AncestryThirdUp {
	return ArticleGenericGR3AncestryThirdUp{
		ArticleRef: v,
	}
}

// ERRORUNKNOWNAsArticleGenericGR3AncestryThirdUp is a convenience function that returns ERRORUNKNOWN wrapped in ArticleGenericGR3AncestryThirdUp
func ERRORUNKNOWNAsArticleGenericGR3AncestryThirdUp(v *ERRORUNKNOWN) ArticleGenericGR3AncestryThirdUp {
	return ArticleGenericGR3AncestryThirdUp{
		ERRORUNKNOWN: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ArticleGenericGR3AncestryThirdUp) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into ArticleRef
	err = newStrictDecoder(data).Decode(&dst.ArticleRef)
	if err == nil {
		jsonArticleRef, _ := json.Marshal(dst.ArticleRef)
		if string(jsonArticleRef) == "{}" { // empty struct
			dst.ArticleRef = nil
		} else {
			if err = validator.Validate(dst.ArticleRef); err != nil {
				dst.ArticleRef = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArticleRef = nil
	}

	// try to unmarshal data into ERRORUNKNOWN
	err = newStrictDecoder(data).Decode(&dst.ERRORUNKNOWN)
	if err == nil {
		jsonERRORUNKNOWN, _ := json.Marshal(dst.ERRORUNKNOWN)
		if string(jsonERRORUNKNOWN) == "{}" { // empty struct
			dst.ERRORUNKNOWN = nil
		} else {
			if err = validator.Validate(dst.ERRORUNKNOWN); err != nil {
				dst.ERRORUNKNOWN = nil
			} else {
				match++
			}
		}
	} else {
		dst.ERRORUNKNOWN = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArticleRef = nil
		dst.ERRORUNKNOWN = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ArticleGenericGR3AncestryThirdUp)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ArticleGenericGR3AncestryThirdUp)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ArticleGenericGR3AncestryThirdUp) MarshalJSON() ([]byte, error) {
	if src.ArticleRef != nil {
		return json.Marshal(&src.ArticleRef)
	}

	if src.ERRORUNKNOWN != nil {
		return json.Marshal(&src.ERRORUNKNOWN)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ArticleGenericGR3AncestryThirdUp) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArticleRef != nil {
		return obj.ArticleRef
	}

	if obj.ERRORUNKNOWN != nil {
		return obj.ERRORUNKNOWN
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ArticleGenericGR3AncestryThirdUp) GetActualInstanceValue() (interface{}) {
	if obj.ArticleRef != nil {
		return *obj.ArticleRef
	}

	if obj.ERRORUNKNOWN != nil {
		return *obj.ERRORUNKNOWN
	}

	// all schemas are nil
	return nil
}

type NullableArticleGenericGR3AncestryThirdUp struct {
	value *ArticleGenericGR3AncestryThirdUp
	isSet bool
}

func (v NullableArticleGenericGR3AncestryThirdUp) Get() *ArticleGenericGR3AncestryThirdUp {
	return v.value
}

func (v *NullableArticleGenericGR3AncestryThirdUp) Set(val *ArticleGenericGR3AncestryThirdUp) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleGenericGR3AncestryThirdUp) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleGenericGR3AncestryThirdUp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleGenericGR3AncestryThirdUp(val *ArticleGenericGR3AncestryThirdUp) *NullableArticleGenericGR3AncestryThirdUp {
	return &NullableArticleGenericGR3AncestryThirdUp{value: val, isSet: true}
}

func (v NullableArticleGenericGR3AncestryThirdUp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleGenericGR3AncestryThirdUp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


