/*
World Anvil Public API Documentation

Welcome to the World Anvil Public API Documentation. This API provides developers and World Anvil users with programmatic access to the extensive features of the World Anvil worldbuilding platform. Whether you're building integrations, automating tasks, or creating custom experiences, this API empowers you to interact with your worldbuilding data seamlessly.

API version: 2.0.0 - Boromir
Contact: contact@worldanvil.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package worldanvil

import (
	"encoding/json"
)

// checks if the BlockRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockRef{}

// BlockRef Metdata of a block.
type BlockRef struct {
	Id *int32 `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Slug NullableString `json:"slug,omitempty"`
	State *string `json:"state,omitempty"`
	IsWip NullableString `json:"isWip,omitempty"`
	IsDraft NullableString `json:"isDraft,omitempty"`
	EntityClass *string `json:"entityClass,omitempty"`
	Icon *string `json:"icon,omitempty"`
	Url *string `json:"url,omitempty"`
	Subscribergroups []string `json:"subscribergroups,omitempty"`
	FolderId NullableString `json:"folderId,omitempty"`
	Tags *string `json:"tags,omitempty"`
	UpdateDate *Object `json:"updateDate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BlockRef BlockRef

// NewBlockRef instantiates a new BlockRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockRef() *BlockRef {
	this := BlockRef{}
	return &this
}

// NewBlockRefWithDefaults instantiates a new BlockRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockRefWithDefaults() *BlockRef {
	this := BlockRef{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BlockRef) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockRef) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BlockRef) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *BlockRef) SetId(v int32) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *BlockRef) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockRef) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *BlockRef) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *BlockRef) SetTitle(v string) {
	o.Title = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlockRef) GetSlug() string {
	if o == nil || IsNil(o.Slug.Get()) {
		var ret string
		return ret
	}
	return *o.Slug.Get()
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlockRef) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Slug.Get(), o.Slug.IsSet()
}

// HasSlug returns a boolean if a field has been set.
func (o *BlockRef) HasSlug() bool {
	if o != nil && o.Slug.IsSet() {
		return true
	}

	return false
}

// SetSlug gets a reference to the given NullableString and assigns it to the Slug field.
func (o *BlockRef) SetSlug(v string) {
	o.Slug.Set(&v)
}
// SetSlugNil sets the value for Slug to be an explicit nil
func (o *BlockRef) SetSlugNil() {
	o.Slug.Set(nil)
}

// UnsetSlug ensures that no value is present for Slug, not even an explicit nil
func (o *BlockRef) UnsetSlug() {
	o.Slug.Unset()
}

// GetState returns the State field value if set, zero value otherwise.
func (o *BlockRef) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockRef) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *BlockRef) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *BlockRef) SetState(v string) {
	o.State = &v
}

// GetIsWip returns the IsWip field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlockRef) GetIsWip() string {
	if o == nil || IsNil(o.IsWip.Get()) {
		var ret string
		return ret
	}
	return *o.IsWip.Get()
}

// GetIsWipOk returns a tuple with the IsWip field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlockRef) GetIsWipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsWip.Get(), o.IsWip.IsSet()
}

// HasIsWip returns a boolean if a field has been set.
func (o *BlockRef) HasIsWip() bool {
	if o != nil && o.IsWip.IsSet() {
		return true
	}

	return false
}

// SetIsWip gets a reference to the given NullableString and assigns it to the IsWip field.
func (o *BlockRef) SetIsWip(v string) {
	o.IsWip.Set(&v)
}
// SetIsWipNil sets the value for IsWip to be an explicit nil
func (o *BlockRef) SetIsWipNil() {
	o.IsWip.Set(nil)
}

// UnsetIsWip ensures that no value is present for IsWip, not even an explicit nil
func (o *BlockRef) UnsetIsWip() {
	o.IsWip.Unset()
}

// GetIsDraft returns the IsDraft field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlockRef) GetIsDraft() string {
	if o == nil || IsNil(o.IsDraft.Get()) {
		var ret string
		return ret
	}
	return *o.IsDraft.Get()
}

// GetIsDraftOk returns a tuple with the IsDraft field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlockRef) GetIsDraftOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsDraft.Get(), o.IsDraft.IsSet()
}

// HasIsDraft returns a boolean if a field has been set.
func (o *BlockRef) HasIsDraft() bool {
	if o != nil && o.IsDraft.IsSet() {
		return true
	}

	return false
}

// SetIsDraft gets a reference to the given NullableString and assigns it to the IsDraft field.
func (o *BlockRef) SetIsDraft(v string) {
	o.IsDraft.Set(&v)
}
// SetIsDraftNil sets the value for IsDraft to be an explicit nil
func (o *BlockRef) SetIsDraftNil() {
	o.IsDraft.Set(nil)
}

// UnsetIsDraft ensures that no value is present for IsDraft, not even an explicit nil
func (o *BlockRef) UnsetIsDraft() {
	o.IsDraft.Unset()
}

// GetEntityClass returns the EntityClass field value if set, zero value otherwise.
func (o *BlockRef) GetEntityClass() string {
	if o == nil || IsNil(o.EntityClass) {
		var ret string
		return ret
	}
	return *o.EntityClass
}

// GetEntityClassOk returns a tuple with the EntityClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockRef) GetEntityClassOk() (*string, bool) {
	if o == nil || IsNil(o.EntityClass) {
		return nil, false
	}
	return o.EntityClass, true
}

// HasEntityClass returns a boolean if a field has been set.
func (o *BlockRef) HasEntityClass() bool {
	if o != nil && !IsNil(o.EntityClass) {
		return true
	}

	return false
}

// SetEntityClass gets a reference to the given string and assigns it to the EntityClass field.
func (o *BlockRef) SetEntityClass(v string) {
	o.EntityClass = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *BlockRef) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockRef) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *BlockRef) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *BlockRef) SetIcon(v string) {
	o.Icon = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BlockRef) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockRef) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BlockRef) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BlockRef) SetUrl(v string) {
	o.Url = &v
}

// GetSubscribergroups returns the Subscribergroups field value if set, zero value otherwise.
func (o *BlockRef) GetSubscribergroups() []string {
	if o == nil || IsNil(o.Subscribergroups) {
		var ret []string
		return ret
	}
	return o.Subscribergroups
}

// GetSubscribergroupsOk returns a tuple with the Subscribergroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockRef) GetSubscribergroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.Subscribergroups) {
		return nil, false
	}
	return o.Subscribergroups, true
}

// HasSubscribergroups returns a boolean if a field has been set.
func (o *BlockRef) HasSubscribergroups() bool {
	if o != nil && !IsNil(o.Subscribergroups) {
		return true
	}

	return false
}

// SetSubscribergroups gets a reference to the given []string and assigns it to the Subscribergroups field.
func (o *BlockRef) SetSubscribergroups(v []string) {
	o.Subscribergroups = v
}

// GetFolderId returns the FolderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlockRef) GetFolderId() string {
	if o == nil || IsNil(o.FolderId.Get()) {
		var ret string
		return ret
	}
	return *o.FolderId.Get()
}

// GetFolderIdOk returns a tuple with the FolderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlockRef) GetFolderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FolderId.Get(), o.FolderId.IsSet()
}

// HasFolderId returns a boolean if a field has been set.
func (o *BlockRef) HasFolderId() bool {
	if o != nil && o.FolderId.IsSet() {
		return true
	}

	return false
}

// SetFolderId gets a reference to the given NullableString and assigns it to the FolderId field.
func (o *BlockRef) SetFolderId(v string) {
	o.FolderId.Set(&v)
}
// SetFolderIdNil sets the value for FolderId to be an explicit nil
func (o *BlockRef) SetFolderIdNil() {
	o.FolderId.Set(nil)
}

// UnsetFolderId ensures that no value is present for FolderId, not even an explicit nil
func (o *BlockRef) UnsetFolderId() {
	o.FolderId.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *BlockRef) GetTags() string {
	if o == nil || IsNil(o.Tags) {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockRef) GetTagsOk() (*string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *BlockRef) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *BlockRef) SetTags(v string) {
	o.Tags = &v
}

// GetUpdateDate returns the UpdateDate field value if set, zero value otherwise.
func (o *BlockRef) GetUpdateDate() Object {
	if o == nil || IsNil(o.UpdateDate) {
		var ret Object
		return ret
	}
	return *o.UpdateDate
}

// GetUpdateDateOk returns a tuple with the UpdateDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockRef) GetUpdateDateOk() (*Object, bool) {
	if o == nil || IsNil(o.UpdateDate) {
		return nil, false
	}
	return o.UpdateDate, true
}

// HasUpdateDate returns a boolean if a field has been set.
func (o *BlockRef) HasUpdateDate() bool {
	if o != nil && !IsNil(o.UpdateDate) {
		return true
	}

	return false
}

// SetUpdateDate gets a reference to the given Object and assigns it to the UpdateDate field.
func (o *BlockRef) SetUpdateDate(v Object) {
	o.UpdateDate = &v
}

func (o BlockRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if o.Slug.IsSet() {
		toSerialize["slug"] = o.Slug.Get()
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if o.IsWip.IsSet() {
		toSerialize["isWip"] = o.IsWip.Get()
	}
	if o.IsDraft.IsSet() {
		toSerialize["isDraft"] = o.IsDraft.Get()
	}
	if !IsNil(o.EntityClass) {
		toSerialize["entityClass"] = o.EntityClass
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Subscribergroups) {
		toSerialize["subscribergroups"] = o.Subscribergroups
	}
	if o.FolderId.IsSet() {
		toSerialize["folderId"] = o.FolderId.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.UpdateDate) {
		toSerialize["updateDate"] = o.UpdateDate
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BlockRef) UnmarshalJSON(data []byte) (err error) {
	varBlockRef := _BlockRef{}

	err = json.Unmarshal(data, &varBlockRef)

	if err != nil {
		return err
	}

	*o = BlockRef(varBlockRef)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "title")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "state")
		delete(additionalProperties, "isWip")
		delete(additionalProperties, "isDraft")
		delete(additionalProperties, "entityClass")
		delete(additionalProperties, "icon")
		delete(additionalProperties, "url")
		delete(additionalProperties, "subscribergroups")
		delete(additionalProperties, "folderId")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "updateDate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBlockRef struct {
	value *BlockRef
	isSet bool
}

func (v NullableBlockRef) Get() *BlockRef {
	return v.value
}

func (v *NullableBlockRef) Set(val *BlockRef) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockRef) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockRef(val *BlockRef) *NullableBlockRef {
	return &NullableBlockRef{value: val, isSet: true}
}

func (v NullableBlockRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


