/*
World Anvil Public API Documentation

Welcome to the World Anvil Public API Documentation. This API provides developers and World Anvil users with programmatic access to the extensive features of the World Anvil worldbuilding platform. Whether you're building integrations, automating tasks, or creating custom experiences, this API empowers you to interact with your worldbuilding data seamlessly.

API version: 2.0.0 - Boromir
Contact: contact@worldanvil.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package worldanvil

import (
	"encoding/json"
)

// checks if the ArticleGenericUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArticleGenericUpdate{}

// ArticleGenericUpdate struct for ArticleGenericUpdate
type ArticleGenericUpdate struct {
	Id *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Slug *string `json:"slug,omitempty"`
	State *string `json:"state,omitempty"`
	IsWip *bool `json:"isWip,omitempty"`
	IsDraft *bool `json:"isDraft,omitempty"`
	EntityClass *string `json:"entityClass,omitempty"`
	Icon NullableString `json:"icon,omitempty"`
	Url *string `json:"url,omitempty"`
	FolderId *string `json:"folderId,omitempty"`
	Tags *string `json:"tags,omitempty"`
	UpdateDate *Object `json:"updateDate,omitempty"`
	Position *int32 `json:"position,omitempty"`
	Excerpt *string `json:"excerpt,omitempty"`
	Wordcount *int32 `json:"wordcount,omitempty"`
	CreationDate *Object `json:"creationDate,omitempty"`
	PublicationDate *Object `json:"publicationDate,omitempty"`
	NotificationDate *Object `json:"notificationDate,omitempty"`
	Likes []Object `json:"likes,omitempty"`
	Views *int32 `json:"views,omitempty"`
	UserMetadata interface{} `json:"userMetadata,omitempty"`
	ArticleMetadata interface{} `json:"articleMetadata,omitempty"`
	CssClasses *string `json:"cssClasses,omitempty"`
	DisplayCss *string `json:"displayCss,omitempty"`
	TemplateType *string `json:"templateType,omitempty"`
	CustomArticleTemplate NullableString `json:"customArticleTemplate,omitempty"`
	Pronunciation *string `json:"pronunciation,omitempty"`
	Snippet *string `json:"snippet,omitempty"`
	Seeded *string `json:"seeded,omitempty"`
	Sidebarcontent *string `json:"sidebarcontent,omitempty"`
	Sidepanelcontenttop *string `json:"sidepanelcontenttop,omitempty"`
	Sidepanelcontent *string `json:"sidepanelcontent,omitempty"`
	Sidebarcontentbottom *string `json:"sidebarcontentbottom,omitempty"`
	Footnotes *string `json:"footnotes,omitempty"`
	Fullfooter *string `json:"fullfooter,omitempty"`
	Authornotes *string `json:"authornotes,omitempty"`
	Scrapbook *string `json:"scrapbook,omitempty"`
	Credits *string `json:"credits,omitempty"`
	DisplaySidebar *bool `json:"displaySidebar,omitempty"`
	Timeline *Object `json:"timeline,omitempty"`
	Prompt *Object `json:"prompt,omitempty"`
	ShowSeeded *bool `json:"showSeeded,omitempty"`
	WebhookUpdate *bool `json:"webhookUpdate,omitempty"`
	CommunityUpdate *bool `json:"communityUpdate,omitempty"`
	CommentPlaceholder NullableString `json:"commentPlaceholder,omitempty"`
	MetaTitle NullableString `json:"metaTitle,omitempty"`
	MetadDescription NullableString `json:"metadDescription,omitempty"`
	Subheading NullableString `json:"subheading,omitempty"`
	CoverIsMap *bool `json:"coverIsMap,omitempty"`
	IsFeaturedArticle *bool `json:"isFeaturedArticle,omitempty"`
	IsAdultContent *bool `json:"isAdultContent,omitempty"`
	IsLocked *bool `json:"isLocked,omitempty"`
	AllowComments *bool `json:"allowComments,omitempty"`
	ShowInToc *bool `json:"showInToc,omitempty"`
	IsEmphasized *bool `json:"isEmphasized,omitempty"`
	DisplayAuthor *bool `json:"displayAuthor,omitempty"`
	DisplayChildrenUnder *bool `json:"displayChildrenUnder,omitempty"`
	DisplayTitle *bool `json:"displayTitle,omitempty"`
	DisplaySheet *bool `json:"displaySheet,omitempty"`
	Badge NullableString `json:"badge,omitempty"`
	Secrets []Object `json:"secrets,omitempty"`
	Histories []Object `json:"histories,omitempty"`
	EditURL *string `json:"editURL,omitempty"`
	Manuscripts []ArticleGenericUpdateObjectPropertiesManuscriptsInner `json:"manuscripts,omitempty"`
	Block *ArticleGenericUpdateObjectPropertiesBlock `json:"block,omitempty"`
	ArticleParent *ArticleGenericUpdateObjectPropertiesManuscriptsInner `json:"articleParent,omitempty"`
	Gallery *ArticleGenericUpdateObjectPropertiesBlock `json:"gallery,omitempty"`
	ArticlePrevious *ArticleGenericUpdateObjectPropertiesManuscriptsInner `json:"articlePrevious,omitempty"`
	ArticleNext *ArticleGenericUpdateObjectPropertiesManuscriptsInner `json:"articleNext,omitempty"`
	Cover *ArticleGenericUpdateObjectPropertiesBlock `json:"cover,omitempty"`
	World *ArticleGenericUpdateObjectPropertiesManuscriptsInner `json:"world,omitempty"`
	Category *ArticleGenericUpdateObjectPropertiesManuscriptsInner `json:"category,omitempty"`
	Author *ArticleGenericUpdateObjectPropertiesManuscriptsInner `json:"author,omitempty"`
	Subscribergroups []ArticleGenericUpdateObjectPropertiesManuscriptsInner `json:"subscribergroups,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ArticleGenericUpdate ArticleGenericUpdate

// NewArticleGenericUpdate instantiates a new ArticleGenericUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleGenericUpdate() *ArticleGenericUpdate {
	this := ArticleGenericUpdate{}
	return &this
}

// NewArticleGenericUpdateWithDefaults instantiates a new ArticleGenericUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleGenericUpdateWithDefaults() *ArticleGenericUpdate {
	this := ArticleGenericUpdate{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ArticleGenericUpdate) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ArticleGenericUpdate) SetTitle(v string) {
	o.Title = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *ArticleGenericUpdate) SetSlug(v string) {
	o.Slug = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ArticleGenericUpdate) SetState(v string) {
	o.State = &v
}

// GetIsWip returns the IsWip field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetIsWip() bool {
	if o == nil || IsNil(o.IsWip) {
		var ret bool
		return ret
	}
	return *o.IsWip
}

// GetIsWipOk returns a tuple with the IsWip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetIsWipOk() (*bool, bool) {
	if o == nil || IsNil(o.IsWip) {
		return nil, false
	}
	return o.IsWip, true
}

// HasIsWip returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasIsWip() bool {
	if o != nil && !IsNil(o.IsWip) {
		return true
	}

	return false
}

// SetIsWip gets a reference to the given bool and assigns it to the IsWip field.
func (o *ArticleGenericUpdate) SetIsWip(v bool) {
	o.IsWip = &v
}

// GetIsDraft returns the IsDraft field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetIsDraft() bool {
	if o == nil || IsNil(o.IsDraft) {
		var ret bool
		return ret
	}
	return *o.IsDraft
}

// GetIsDraftOk returns a tuple with the IsDraft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetIsDraftOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDraft) {
		return nil, false
	}
	return o.IsDraft, true
}

// HasIsDraft returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasIsDraft() bool {
	if o != nil && !IsNil(o.IsDraft) {
		return true
	}

	return false
}

// SetIsDraft gets a reference to the given bool and assigns it to the IsDraft field.
func (o *ArticleGenericUpdate) SetIsDraft(v bool) {
	o.IsDraft = &v
}

// GetEntityClass returns the EntityClass field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetEntityClass() string {
	if o == nil || IsNil(o.EntityClass) {
		var ret string
		return ret
	}
	return *o.EntityClass
}

// GetEntityClassOk returns a tuple with the EntityClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetEntityClassOk() (*string, bool) {
	if o == nil || IsNil(o.EntityClass) {
		return nil, false
	}
	return o.EntityClass, true
}

// HasEntityClass returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasEntityClass() bool {
	if o != nil && !IsNil(o.EntityClass) {
		return true
	}

	return false
}

// SetEntityClass gets a reference to the given string and assigns it to the EntityClass field.
func (o *ArticleGenericUpdate) SetEntityClass(v string) {
	o.EntityClass = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArticleGenericUpdate) GetIcon() string {
	if o == nil || IsNil(o.Icon.Get()) {
		var ret string
		return ret
	}
	return *o.Icon.Get()
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArticleGenericUpdate) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Icon.Get(), o.Icon.IsSet()
}

// HasIcon returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasIcon() bool {
	if o != nil && o.Icon.IsSet() {
		return true
	}

	return false
}

// SetIcon gets a reference to the given NullableString and assigns it to the Icon field.
func (o *ArticleGenericUpdate) SetIcon(v string) {
	o.Icon.Set(&v)
}
// SetIconNil sets the value for Icon to be an explicit nil
func (o *ArticleGenericUpdate) SetIconNil() {
	o.Icon.Set(nil)
}

// UnsetIcon ensures that no value is present for Icon, not even an explicit nil
func (o *ArticleGenericUpdate) UnsetIcon() {
	o.Icon.Unset()
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ArticleGenericUpdate) SetUrl(v string) {
	o.Url = &v
}

// GetFolderId returns the FolderId field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetFolderId() string {
	if o == nil || IsNil(o.FolderId) {
		var ret string
		return ret
	}
	return *o.FolderId
}

// GetFolderIdOk returns a tuple with the FolderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetFolderIdOk() (*string, bool) {
	if o == nil || IsNil(o.FolderId) {
		return nil, false
	}
	return o.FolderId, true
}

// HasFolderId returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasFolderId() bool {
	if o != nil && !IsNil(o.FolderId) {
		return true
	}

	return false
}

// SetFolderId gets a reference to the given string and assigns it to the FolderId field.
func (o *ArticleGenericUpdate) SetFolderId(v string) {
	o.FolderId = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetTags() string {
	if o == nil || IsNil(o.Tags) {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetTagsOk() (*string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *ArticleGenericUpdate) SetTags(v string) {
	o.Tags = &v
}

// GetUpdateDate returns the UpdateDate field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetUpdateDate() Object {
	if o == nil || IsNil(o.UpdateDate) {
		var ret Object
		return ret
	}
	return *o.UpdateDate
}

// GetUpdateDateOk returns a tuple with the UpdateDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetUpdateDateOk() (*Object, bool) {
	if o == nil || IsNil(o.UpdateDate) {
		return nil, false
	}
	return o.UpdateDate, true
}

// HasUpdateDate returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasUpdateDate() bool {
	if o != nil && !IsNil(o.UpdateDate) {
		return true
	}

	return false
}

// SetUpdateDate gets a reference to the given Object and assigns it to the UpdateDate field.
func (o *ArticleGenericUpdate) SetUpdateDate(v Object) {
	o.UpdateDate = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *ArticleGenericUpdate) SetPosition(v int32) {
	o.Position = &v
}

// GetExcerpt returns the Excerpt field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetExcerpt() string {
	if o == nil || IsNil(o.Excerpt) {
		var ret string
		return ret
	}
	return *o.Excerpt
}

// GetExcerptOk returns a tuple with the Excerpt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetExcerptOk() (*string, bool) {
	if o == nil || IsNil(o.Excerpt) {
		return nil, false
	}
	return o.Excerpt, true
}

// HasExcerpt returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasExcerpt() bool {
	if o != nil && !IsNil(o.Excerpt) {
		return true
	}

	return false
}

// SetExcerpt gets a reference to the given string and assigns it to the Excerpt field.
func (o *ArticleGenericUpdate) SetExcerpt(v string) {
	o.Excerpt = &v
}

// GetWordcount returns the Wordcount field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetWordcount() int32 {
	if o == nil || IsNil(o.Wordcount) {
		var ret int32
		return ret
	}
	return *o.Wordcount
}

// GetWordcountOk returns a tuple with the Wordcount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetWordcountOk() (*int32, bool) {
	if o == nil || IsNil(o.Wordcount) {
		return nil, false
	}
	return o.Wordcount, true
}

// HasWordcount returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasWordcount() bool {
	if o != nil && !IsNil(o.Wordcount) {
		return true
	}

	return false
}

// SetWordcount gets a reference to the given int32 and assigns it to the Wordcount field.
func (o *ArticleGenericUpdate) SetWordcount(v int32) {
	o.Wordcount = &v
}

// GetCreationDate returns the CreationDate field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetCreationDate() Object {
	if o == nil || IsNil(o.CreationDate) {
		var ret Object
		return ret
	}
	return *o.CreationDate
}

// GetCreationDateOk returns a tuple with the CreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetCreationDateOk() (*Object, bool) {
	if o == nil || IsNil(o.CreationDate) {
		return nil, false
	}
	return o.CreationDate, true
}

// HasCreationDate returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasCreationDate() bool {
	if o != nil && !IsNil(o.CreationDate) {
		return true
	}

	return false
}

// SetCreationDate gets a reference to the given Object and assigns it to the CreationDate field.
func (o *ArticleGenericUpdate) SetCreationDate(v Object) {
	o.CreationDate = &v
}

// GetPublicationDate returns the PublicationDate field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetPublicationDate() Object {
	if o == nil || IsNil(o.PublicationDate) {
		var ret Object
		return ret
	}
	return *o.PublicationDate
}

// GetPublicationDateOk returns a tuple with the PublicationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetPublicationDateOk() (*Object, bool) {
	if o == nil || IsNil(o.PublicationDate) {
		return nil, false
	}
	return o.PublicationDate, true
}

// HasPublicationDate returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasPublicationDate() bool {
	if o != nil && !IsNil(o.PublicationDate) {
		return true
	}

	return false
}

// SetPublicationDate gets a reference to the given Object and assigns it to the PublicationDate field.
func (o *ArticleGenericUpdate) SetPublicationDate(v Object) {
	o.PublicationDate = &v
}

// GetNotificationDate returns the NotificationDate field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetNotificationDate() Object {
	if o == nil || IsNil(o.NotificationDate) {
		var ret Object
		return ret
	}
	return *o.NotificationDate
}

// GetNotificationDateOk returns a tuple with the NotificationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetNotificationDateOk() (*Object, bool) {
	if o == nil || IsNil(o.NotificationDate) {
		return nil, false
	}
	return o.NotificationDate, true
}

// HasNotificationDate returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasNotificationDate() bool {
	if o != nil && !IsNil(o.NotificationDate) {
		return true
	}

	return false
}

// SetNotificationDate gets a reference to the given Object and assigns it to the NotificationDate field.
func (o *ArticleGenericUpdate) SetNotificationDate(v Object) {
	o.NotificationDate = &v
}

// GetLikes returns the Likes field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetLikes() []Object {
	if o == nil || IsNil(o.Likes) {
		var ret []Object
		return ret
	}
	return o.Likes
}

// GetLikesOk returns a tuple with the Likes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetLikesOk() ([]Object, bool) {
	if o == nil || IsNil(o.Likes) {
		return nil, false
	}
	return o.Likes, true
}

// HasLikes returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasLikes() bool {
	if o != nil && !IsNil(o.Likes) {
		return true
	}

	return false
}

// SetLikes gets a reference to the given []Object and assigns it to the Likes field.
func (o *ArticleGenericUpdate) SetLikes(v []Object) {
	o.Likes = v
}

// GetViews returns the Views field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetViews() int32 {
	if o == nil || IsNil(o.Views) {
		var ret int32
		return ret
	}
	return *o.Views
}

// GetViewsOk returns a tuple with the Views field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetViewsOk() (*int32, bool) {
	if o == nil || IsNil(o.Views) {
		return nil, false
	}
	return o.Views, true
}

// HasViews returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasViews() bool {
	if o != nil && !IsNil(o.Views) {
		return true
	}

	return false
}

// SetViews gets a reference to the given int32 and assigns it to the Views field.
func (o *ArticleGenericUpdate) SetViews(v int32) {
	o.Views = &v
}

// GetUserMetadata returns the UserMetadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArticleGenericUpdate) GetUserMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.UserMetadata
}

// GetUserMetadataOk returns a tuple with the UserMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArticleGenericUpdate) GetUserMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UserMetadata) {
		return nil, false
	}
	return &o.UserMetadata, true
}

// HasUserMetadata returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasUserMetadata() bool {
	if o != nil && !IsNil(o.UserMetadata) {
		return true
	}

	return false
}

// SetUserMetadata gets a reference to the given interface{} and assigns it to the UserMetadata field.
func (o *ArticleGenericUpdate) SetUserMetadata(v interface{}) {
	o.UserMetadata = v
}

// GetArticleMetadata returns the ArticleMetadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArticleGenericUpdate) GetArticleMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ArticleMetadata
}

// GetArticleMetadataOk returns a tuple with the ArticleMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArticleGenericUpdate) GetArticleMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ArticleMetadata) {
		return nil, false
	}
	return &o.ArticleMetadata, true
}

// HasArticleMetadata returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasArticleMetadata() bool {
	if o != nil && !IsNil(o.ArticleMetadata) {
		return true
	}

	return false
}

// SetArticleMetadata gets a reference to the given interface{} and assigns it to the ArticleMetadata field.
func (o *ArticleGenericUpdate) SetArticleMetadata(v interface{}) {
	o.ArticleMetadata = v
}

// GetCssClasses returns the CssClasses field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetCssClasses() string {
	if o == nil || IsNil(o.CssClasses) {
		var ret string
		return ret
	}
	return *o.CssClasses
}

// GetCssClassesOk returns a tuple with the CssClasses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetCssClassesOk() (*string, bool) {
	if o == nil || IsNil(o.CssClasses) {
		return nil, false
	}
	return o.CssClasses, true
}

// HasCssClasses returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasCssClasses() bool {
	if o != nil && !IsNil(o.CssClasses) {
		return true
	}

	return false
}

// SetCssClasses gets a reference to the given string and assigns it to the CssClasses field.
func (o *ArticleGenericUpdate) SetCssClasses(v string) {
	o.CssClasses = &v
}

// GetDisplayCss returns the DisplayCss field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetDisplayCss() string {
	if o == nil || IsNil(o.DisplayCss) {
		var ret string
		return ret
	}
	return *o.DisplayCss
}

// GetDisplayCssOk returns a tuple with the DisplayCss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetDisplayCssOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayCss) {
		return nil, false
	}
	return o.DisplayCss, true
}

// HasDisplayCss returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasDisplayCss() bool {
	if o != nil && !IsNil(o.DisplayCss) {
		return true
	}

	return false
}

// SetDisplayCss gets a reference to the given string and assigns it to the DisplayCss field.
func (o *ArticleGenericUpdate) SetDisplayCss(v string) {
	o.DisplayCss = &v
}

// GetTemplateType returns the TemplateType field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetTemplateType() string {
	if o == nil || IsNil(o.TemplateType) {
		var ret string
		return ret
	}
	return *o.TemplateType
}

// GetTemplateTypeOk returns a tuple with the TemplateType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetTemplateTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateType) {
		return nil, false
	}
	return o.TemplateType, true
}

// HasTemplateType returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasTemplateType() bool {
	if o != nil && !IsNil(o.TemplateType) {
		return true
	}

	return false
}

// SetTemplateType gets a reference to the given string and assigns it to the TemplateType field.
func (o *ArticleGenericUpdate) SetTemplateType(v string) {
	o.TemplateType = &v
}

// GetCustomArticleTemplate returns the CustomArticleTemplate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArticleGenericUpdate) GetCustomArticleTemplate() string {
	if o == nil || IsNil(o.CustomArticleTemplate.Get()) {
		var ret string
		return ret
	}
	return *o.CustomArticleTemplate.Get()
}

// GetCustomArticleTemplateOk returns a tuple with the CustomArticleTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArticleGenericUpdate) GetCustomArticleTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomArticleTemplate.Get(), o.CustomArticleTemplate.IsSet()
}

// HasCustomArticleTemplate returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasCustomArticleTemplate() bool {
	if o != nil && o.CustomArticleTemplate.IsSet() {
		return true
	}

	return false
}

// SetCustomArticleTemplate gets a reference to the given NullableString and assigns it to the CustomArticleTemplate field.
func (o *ArticleGenericUpdate) SetCustomArticleTemplate(v string) {
	o.CustomArticleTemplate.Set(&v)
}
// SetCustomArticleTemplateNil sets the value for CustomArticleTemplate to be an explicit nil
func (o *ArticleGenericUpdate) SetCustomArticleTemplateNil() {
	o.CustomArticleTemplate.Set(nil)
}

// UnsetCustomArticleTemplate ensures that no value is present for CustomArticleTemplate, not even an explicit nil
func (o *ArticleGenericUpdate) UnsetCustomArticleTemplate() {
	o.CustomArticleTemplate.Unset()
}

// GetPronunciation returns the Pronunciation field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetPronunciation() string {
	if o == nil || IsNil(o.Pronunciation) {
		var ret string
		return ret
	}
	return *o.Pronunciation
}

// GetPronunciationOk returns a tuple with the Pronunciation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetPronunciationOk() (*string, bool) {
	if o == nil || IsNil(o.Pronunciation) {
		return nil, false
	}
	return o.Pronunciation, true
}

// HasPronunciation returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasPronunciation() bool {
	if o != nil && !IsNil(o.Pronunciation) {
		return true
	}

	return false
}

// SetPronunciation gets a reference to the given string and assigns it to the Pronunciation field.
func (o *ArticleGenericUpdate) SetPronunciation(v string) {
	o.Pronunciation = &v
}

// GetSnippet returns the Snippet field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetSnippet() string {
	if o == nil || IsNil(o.Snippet) {
		var ret string
		return ret
	}
	return *o.Snippet
}

// GetSnippetOk returns a tuple with the Snippet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetSnippetOk() (*string, bool) {
	if o == nil || IsNil(o.Snippet) {
		return nil, false
	}
	return o.Snippet, true
}

// HasSnippet returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasSnippet() bool {
	if o != nil && !IsNil(o.Snippet) {
		return true
	}

	return false
}

// SetSnippet gets a reference to the given string and assigns it to the Snippet field.
func (o *ArticleGenericUpdate) SetSnippet(v string) {
	o.Snippet = &v
}

// GetSeeded returns the Seeded field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetSeeded() string {
	if o == nil || IsNil(o.Seeded) {
		var ret string
		return ret
	}
	return *o.Seeded
}

// GetSeededOk returns a tuple with the Seeded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetSeededOk() (*string, bool) {
	if o == nil || IsNil(o.Seeded) {
		return nil, false
	}
	return o.Seeded, true
}

// HasSeeded returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasSeeded() bool {
	if o != nil && !IsNil(o.Seeded) {
		return true
	}

	return false
}

// SetSeeded gets a reference to the given string and assigns it to the Seeded field.
func (o *ArticleGenericUpdate) SetSeeded(v string) {
	o.Seeded = &v
}

// GetSidebarcontent returns the Sidebarcontent field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetSidebarcontent() string {
	if o == nil || IsNil(o.Sidebarcontent) {
		var ret string
		return ret
	}
	return *o.Sidebarcontent
}

// GetSidebarcontentOk returns a tuple with the Sidebarcontent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetSidebarcontentOk() (*string, bool) {
	if o == nil || IsNil(o.Sidebarcontent) {
		return nil, false
	}
	return o.Sidebarcontent, true
}

// HasSidebarcontent returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasSidebarcontent() bool {
	if o != nil && !IsNil(o.Sidebarcontent) {
		return true
	}

	return false
}

// SetSidebarcontent gets a reference to the given string and assigns it to the Sidebarcontent field.
func (o *ArticleGenericUpdate) SetSidebarcontent(v string) {
	o.Sidebarcontent = &v
}

// GetSidepanelcontenttop returns the Sidepanelcontenttop field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetSidepanelcontenttop() string {
	if o == nil || IsNil(o.Sidepanelcontenttop) {
		var ret string
		return ret
	}
	return *o.Sidepanelcontenttop
}

// GetSidepanelcontenttopOk returns a tuple with the Sidepanelcontenttop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetSidepanelcontenttopOk() (*string, bool) {
	if o == nil || IsNil(o.Sidepanelcontenttop) {
		return nil, false
	}
	return o.Sidepanelcontenttop, true
}

// HasSidepanelcontenttop returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasSidepanelcontenttop() bool {
	if o != nil && !IsNil(o.Sidepanelcontenttop) {
		return true
	}

	return false
}

// SetSidepanelcontenttop gets a reference to the given string and assigns it to the Sidepanelcontenttop field.
func (o *ArticleGenericUpdate) SetSidepanelcontenttop(v string) {
	o.Sidepanelcontenttop = &v
}

// GetSidepanelcontent returns the Sidepanelcontent field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetSidepanelcontent() string {
	if o == nil || IsNil(o.Sidepanelcontent) {
		var ret string
		return ret
	}
	return *o.Sidepanelcontent
}

// GetSidepanelcontentOk returns a tuple with the Sidepanelcontent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetSidepanelcontentOk() (*string, bool) {
	if o == nil || IsNil(o.Sidepanelcontent) {
		return nil, false
	}
	return o.Sidepanelcontent, true
}

// HasSidepanelcontent returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasSidepanelcontent() bool {
	if o != nil && !IsNil(o.Sidepanelcontent) {
		return true
	}

	return false
}

// SetSidepanelcontent gets a reference to the given string and assigns it to the Sidepanelcontent field.
func (o *ArticleGenericUpdate) SetSidepanelcontent(v string) {
	o.Sidepanelcontent = &v
}

// GetSidebarcontentbottom returns the Sidebarcontentbottom field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetSidebarcontentbottom() string {
	if o == nil || IsNil(o.Sidebarcontentbottom) {
		var ret string
		return ret
	}
	return *o.Sidebarcontentbottom
}

// GetSidebarcontentbottomOk returns a tuple with the Sidebarcontentbottom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetSidebarcontentbottomOk() (*string, bool) {
	if o == nil || IsNil(o.Sidebarcontentbottom) {
		return nil, false
	}
	return o.Sidebarcontentbottom, true
}

// HasSidebarcontentbottom returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasSidebarcontentbottom() bool {
	if o != nil && !IsNil(o.Sidebarcontentbottom) {
		return true
	}

	return false
}

// SetSidebarcontentbottom gets a reference to the given string and assigns it to the Sidebarcontentbottom field.
func (o *ArticleGenericUpdate) SetSidebarcontentbottom(v string) {
	o.Sidebarcontentbottom = &v
}

// GetFootnotes returns the Footnotes field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetFootnotes() string {
	if o == nil || IsNil(o.Footnotes) {
		var ret string
		return ret
	}
	return *o.Footnotes
}

// GetFootnotesOk returns a tuple with the Footnotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetFootnotesOk() (*string, bool) {
	if o == nil || IsNil(o.Footnotes) {
		return nil, false
	}
	return o.Footnotes, true
}

// HasFootnotes returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasFootnotes() bool {
	if o != nil && !IsNil(o.Footnotes) {
		return true
	}

	return false
}

// SetFootnotes gets a reference to the given string and assigns it to the Footnotes field.
func (o *ArticleGenericUpdate) SetFootnotes(v string) {
	o.Footnotes = &v
}

// GetFullfooter returns the Fullfooter field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetFullfooter() string {
	if o == nil || IsNil(o.Fullfooter) {
		var ret string
		return ret
	}
	return *o.Fullfooter
}

// GetFullfooterOk returns a tuple with the Fullfooter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetFullfooterOk() (*string, bool) {
	if o == nil || IsNil(o.Fullfooter) {
		return nil, false
	}
	return o.Fullfooter, true
}

// HasFullfooter returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasFullfooter() bool {
	if o != nil && !IsNil(o.Fullfooter) {
		return true
	}

	return false
}

// SetFullfooter gets a reference to the given string and assigns it to the Fullfooter field.
func (o *ArticleGenericUpdate) SetFullfooter(v string) {
	o.Fullfooter = &v
}

// GetAuthornotes returns the Authornotes field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetAuthornotes() string {
	if o == nil || IsNil(o.Authornotes) {
		var ret string
		return ret
	}
	return *o.Authornotes
}

// GetAuthornotesOk returns a tuple with the Authornotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetAuthornotesOk() (*string, bool) {
	if o == nil || IsNil(o.Authornotes) {
		return nil, false
	}
	return o.Authornotes, true
}

// HasAuthornotes returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasAuthornotes() bool {
	if o != nil && !IsNil(o.Authornotes) {
		return true
	}

	return false
}

// SetAuthornotes gets a reference to the given string and assigns it to the Authornotes field.
func (o *ArticleGenericUpdate) SetAuthornotes(v string) {
	o.Authornotes = &v
}

// GetScrapbook returns the Scrapbook field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetScrapbook() string {
	if o == nil || IsNil(o.Scrapbook) {
		var ret string
		return ret
	}
	return *o.Scrapbook
}

// GetScrapbookOk returns a tuple with the Scrapbook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetScrapbookOk() (*string, bool) {
	if o == nil || IsNil(o.Scrapbook) {
		return nil, false
	}
	return o.Scrapbook, true
}

// HasScrapbook returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasScrapbook() bool {
	if o != nil && !IsNil(o.Scrapbook) {
		return true
	}

	return false
}

// SetScrapbook gets a reference to the given string and assigns it to the Scrapbook field.
func (o *ArticleGenericUpdate) SetScrapbook(v string) {
	o.Scrapbook = &v
}

// GetCredits returns the Credits field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetCredits() string {
	if o == nil || IsNil(o.Credits) {
		var ret string
		return ret
	}
	return *o.Credits
}

// GetCreditsOk returns a tuple with the Credits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetCreditsOk() (*string, bool) {
	if o == nil || IsNil(o.Credits) {
		return nil, false
	}
	return o.Credits, true
}

// HasCredits returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasCredits() bool {
	if o != nil && !IsNil(o.Credits) {
		return true
	}

	return false
}

// SetCredits gets a reference to the given string and assigns it to the Credits field.
func (o *ArticleGenericUpdate) SetCredits(v string) {
	o.Credits = &v
}

// GetDisplaySidebar returns the DisplaySidebar field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetDisplaySidebar() bool {
	if o == nil || IsNil(o.DisplaySidebar) {
		var ret bool
		return ret
	}
	return *o.DisplaySidebar
}

// GetDisplaySidebarOk returns a tuple with the DisplaySidebar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetDisplaySidebarOk() (*bool, bool) {
	if o == nil || IsNil(o.DisplaySidebar) {
		return nil, false
	}
	return o.DisplaySidebar, true
}

// HasDisplaySidebar returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasDisplaySidebar() bool {
	if o != nil && !IsNil(o.DisplaySidebar) {
		return true
	}

	return false
}

// SetDisplaySidebar gets a reference to the given bool and assigns it to the DisplaySidebar field.
func (o *ArticleGenericUpdate) SetDisplaySidebar(v bool) {
	o.DisplaySidebar = &v
}

// GetTimeline returns the Timeline field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetTimeline() Object {
	if o == nil || IsNil(o.Timeline) {
		var ret Object
		return ret
	}
	return *o.Timeline
}

// GetTimelineOk returns a tuple with the Timeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetTimelineOk() (*Object, bool) {
	if o == nil || IsNil(o.Timeline) {
		return nil, false
	}
	return o.Timeline, true
}

// HasTimeline returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasTimeline() bool {
	if o != nil && !IsNil(o.Timeline) {
		return true
	}

	return false
}

// SetTimeline gets a reference to the given Object and assigns it to the Timeline field.
func (o *ArticleGenericUpdate) SetTimeline(v Object) {
	o.Timeline = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetPrompt() Object {
	if o == nil || IsNil(o.Prompt) {
		var ret Object
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetPromptOk() (*Object, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given Object and assigns it to the Prompt field.
func (o *ArticleGenericUpdate) SetPrompt(v Object) {
	o.Prompt = &v
}

// GetShowSeeded returns the ShowSeeded field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetShowSeeded() bool {
	if o == nil || IsNil(o.ShowSeeded) {
		var ret bool
		return ret
	}
	return *o.ShowSeeded
}

// GetShowSeededOk returns a tuple with the ShowSeeded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetShowSeededOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowSeeded) {
		return nil, false
	}
	return o.ShowSeeded, true
}

// HasShowSeeded returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasShowSeeded() bool {
	if o != nil && !IsNil(o.ShowSeeded) {
		return true
	}

	return false
}

// SetShowSeeded gets a reference to the given bool and assigns it to the ShowSeeded field.
func (o *ArticleGenericUpdate) SetShowSeeded(v bool) {
	o.ShowSeeded = &v
}

// GetWebhookUpdate returns the WebhookUpdate field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetWebhookUpdate() bool {
	if o == nil || IsNil(o.WebhookUpdate) {
		var ret bool
		return ret
	}
	return *o.WebhookUpdate
}

// GetWebhookUpdateOk returns a tuple with the WebhookUpdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetWebhookUpdateOk() (*bool, bool) {
	if o == nil || IsNil(o.WebhookUpdate) {
		return nil, false
	}
	return o.WebhookUpdate, true
}

// HasWebhookUpdate returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasWebhookUpdate() bool {
	if o != nil && !IsNil(o.WebhookUpdate) {
		return true
	}

	return false
}

// SetWebhookUpdate gets a reference to the given bool and assigns it to the WebhookUpdate field.
func (o *ArticleGenericUpdate) SetWebhookUpdate(v bool) {
	o.WebhookUpdate = &v
}

// GetCommunityUpdate returns the CommunityUpdate field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetCommunityUpdate() bool {
	if o == nil || IsNil(o.CommunityUpdate) {
		var ret bool
		return ret
	}
	return *o.CommunityUpdate
}

// GetCommunityUpdateOk returns a tuple with the CommunityUpdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetCommunityUpdateOk() (*bool, bool) {
	if o == nil || IsNil(o.CommunityUpdate) {
		return nil, false
	}
	return o.CommunityUpdate, true
}

// HasCommunityUpdate returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasCommunityUpdate() bool {
	if o != nil && !IsNil(o.CommunityUpdate) {
		return true
	}

	return false
}

// SetCommunityUpdate gets a reference to the given bool and assigns it to the CommunityUpdate field.
func (o *ArticleGenericUpdate) SetCommunityUpdate(v bool) {
	o.CommunityUpdate = &v
}

// GetCommentPlaceholder returns the CommentPlaceholder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArticleGenericUpdate) GetCommentPlaceholder() string {
	if o == nil || IsNil(o.CommentPlaceholder.Get()) {
		var ret string
		return ret
	}
	return *o.CommentPlaceholder.Get()
}

// GetCommentPlaceholderOk returns a tuple with the CommentPlaceholder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArticleGenericUpdate) GetCommentPlaceholderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CommentPlaceholder.Get(), o.CommentPlaceholder.IsSet()
}

// HasCommentPlaceholder returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasCommentPlaceholder() bool {
	if o != nil && o.CommentPlaceholder.IsSet() {
		return true
	}

	return false
}

// SetCommentPlaceholder gets a reference to the given NullableString and assigns it to the CommentPlaceholder field.
func (o *ArticleGenericUpdate) SetCommentPlaceholder(v string) {
	o.CommentPlaceholder.Set(&v)
}
// SetCommentPlaceholderNil sets the value for CommentPlaceholder to be an explicit nil
func (o *ArticleGenericUpdate) SetCommentPlaceholderNil() {
	o.CommentPlaceholder.Set(nil)
}

// UnsetCommentPlaceholder ensures that no value is present for CommentPlaceholder, not even an explicit nil
func (o *ArticleGenericUpdate) UnsetCommentPlaceholder() {
	o.CommentPlaceholder.Unset()
}

// GetMetaTitle returns the MetaTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArticleGenericUpdate) GetMetaTitle() string {
	if o == nil || IsNil(o.MetaTitle.Get()) {
		var ret string
		return ret
	}
	return *o.MetaTitle.Get()
}

// GetMetaTitleOk returns a tuple with the MetaTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArticleGenericUpdate) GetMetaTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetaTitle.Get(), o.MetaTitle.IsSet()
}

// HasMetaTitle returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasMetaTitle() bool {
	if o != nil && o.MetaTitle.IsSet() {
		return true
	}

	return false
}

// SetMetaTitle gets a reference to the given NullableString and assigns it to the MetaTitle field.
func (o *ArticleGenericUpdate) SetMetaTitle(v string) {
	o.MetaTitle.Set(&v)
}
// SetMetaTitleNil sets the value for MetaTitle to be an explicit nil
func (o *ArticleGenericUpdate) SetMetaTitleNil() {
	o.MetaTitle.Set(nil)
}

// UnsetMetaTitle ensures that no value is present for MetaTitle, not even an explicit nil
func (o *ArticleGenericUpdate) UnsetMetaTitle() {
	o.MetaTitle.Unset()
}

// GetMetadDescription returns the MetadDescription field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArticleGenericUpdate) GetMetadDescription() string {
	if o == nil || IsNil(o.MetadDescription.Get()) {
		var ret string
		return ret
	}
	return *o.MetadDescription.Get()
}

// GetMetadDescriptionOk returns a tuple with the MetadDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArticleGenericUpdate) GetMetadDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetadDescription.Get(), o.MetadDescription.IsSet()
}

// HasMetadDescription returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasMetadDescription() bool {
	if o != nil && o.MetadDescription.IsSet() {
		return true
	}

	return false
}

// SetMetadDescription gets a reference to the given NullableString and assigns it to the MetadDescription field.
func (o *ArticleGenericUpdate) SetMetadDescription(v string) {
	o.MetadDescription.Set(&v)
}
// SetMetadDescriptionNil sets the value for MetadDescription to be an explicit nil
func (o *ArticleGenericUpdate) SetMetadDescriptionNil() {
	o.MetadDescription.Set(nil)
}

// UnsetMetadDescription ensures that no value is present for MetadDescription, not even an explicit nil
func (o *ArticleGenericUpdate) UnsetMetadDescription() {
	o.MetadDescription.Unset()
}

// GetSubheading returns the Subheading field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArticleGenericUpdate) GetSubheading() string {
	if o == nil || IsNil(o.Subheading.Get()) {
		var ret string
		return ret
	}
	return *o.Subheading.Get()
}

// GetSubheadingOk returns a tuple with the Subheading field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArticleGenericUpdate) GetSubheadingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subheading.Get(), o.Subheading.IsSet()
}

// HasSubheading returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasSubheading() bool {
	if o != nil && o.Subheading.IsSet() {
		return true
	}

	return false
}

// SetSubheading gets a reference to the given NullableString and assigns it to the Subheading field.
func (o *ArticleGenericUpdate) SetSubheading(v string) {
	o.Subheading.Set(&v)
}
// SetSubheadingNil sets the value for Subheading to be an explicit nil
func (o *ArticleGenericUpdate) SetSubheadingNil() {
	o.Subheading.Set(nil)
}

// UnsetSubheading ensures that no value is present for Subheading, not even an explicit nil
func (o *ArticleGenericUpdate) UnsetSubheading() {
	o.Subheading.Unset()
}

// GetCoverIsMap returns the CoverIsMap field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetCoverIsMap() bool {
	if o == nil || IsNil(o.CoverIsMap) {
		var ret bool
		return ret
	}
	return *o.CoverIsMap
}

// GetCoverIsMapOk returns a tuple with the CoverIsMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetCoverIsMapOk() (*bool, bool) {
	if o == nil || IsNil(o.CoverIsMap) {
		return nil, false
	}
	return o.CoverIsMap, true
}

// HasCoverIsMap returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasCoverIsMap() bool {
	if o != nil && !IsNil(o.CoverIsMap) {
		return true
	}

	return false
}

// SetCoverIsMap gets a reference to the given bool and assigns it to the CoverIsMap field.
func (o *ArticleGenericUpdate) SetCoverIsMap(v bool) {
	o.CoverIsMap = &v
}

// GetIsFeaturedArticle returns the IsFeaturedArticle field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetIsFeaturedArticle() bool {
	if o == nil || IsNil(o.IsFeaturedArticle) {
		var ret bool
		return ret
	}
	return *o.IsFeaturedArticle
}

// GetIsFeaturedArticleOk returns a tuple with the IsFeaturedArticle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetIsFeaturedArticleOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFeaturedArticle) {
		return nil, false
	}
	return o.IsFeaturedArticle, true
}

// HasIsFeaturedArticle returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasIsFeaturedArticle() bool {
	if o != nil && !IsNil(o.IsFeaturedArticle) {
		return true
	}

	return false
}

// SetIsFeaturedArticle gets a reference to the given bool and assigns it to the IsFeaturedArticle field.
func (o *ArticleGenericUpdate) SetIsFeaturedArticle(v bool) {
	o.IsFeaturedArticle = &v
}

// GetIsAdultContent returns the IsAdultContent field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetIsAdultContent() bool {
	if o == nil || IsNil(o.IsAdultContent) {
		var ret bool
		return ret
	}
	return *o.IsAdultContent
}

// GetIsAdultContentOk returns a tuple with the IsAdultContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetIsAdultContentOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAdultContent) {
		return nil, false
	}
	return o.IsAdultContent, true
}

// HasIsAdultContent returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasIsAdultContent() bool {
	if o != nil && !IsNil(o.IsAdultContent) {
		return true
	}

	return false
}

// SetIsAdultContent gets a reference to the given bool and assigns it to the IsAdultContent field.
func (o *ArticleGenericUpdate) SetIsAdultContent(v bool) {
	o.IsAdultContent = &v
}

// GetIsLocked returns the IsLocked field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetIsLocked() bool {
	if o == nil || IsNil(o.IsLocked) {
		var ret bool
		return ret
	}
	return *o.IsLocked
}

// GetIsLockedOk returns a tuple with the IsLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetIsLockedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsLocked) {
		return nil, false
	}
	return o.IsLocked, true
}

// HasIsLocked returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasIsLocked() bool {
	if o != nil && !IsNil(o.IsLocked) {
		return true
	}

	return false
}

// SetIsLocked gets a reference to the given bool and assigns it to the IsLocked field.
func (o *ArticleGenericUpdate) SetIsLocked(v bool) {
	o.IsLocked = &v
}

// GetAllowComments returns the AllowComments field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetAllowComments() bool {
	if o == nil || IsNil(o.AllowComments) {
		var ret bool
		return ret
	}
	return *o.AllowComments
}

// GetAllowCommentsOk returns a tuple with the AllowComments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetAllowCommentsOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowComments) {
		return nil, false
	}
	return o.AllowComments, true
}

// HasAllowComments returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasAllowComments() bool {
	if o != nil && !IsNil(o.AllowComments) {
		return true
	}

	return false
}

// SetAllowComments gets a reference to the given bool and assigns it to the AllowComments field.
func (o *ArticleGenericUpdate) SetAllowComments(v bool) {
	o.AllowComments = &v
}

// GetShowInToc returns the ShowInToc field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetShowInToc() bool {
	if o == nil || IsNil(o.ShowInToc) {
		var ret bool
		return ret
	}
	return *o.ShowInToc
}

// GetShowInTocOk returns a tuple with the ShowInToc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetShowInTocOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowInToc) {
		return nil, false
	}
	return o.ShowInToc, true
}

// HasShowInToc returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasShowInToc() bool {
	if o != nil && !IsNil(o.ShowInToc) {
		return true
	}

	return false
}

// SetShowInToc gets a reference to the given bool and assigns it to the ShowInToc field.
func (o *ArticleGenericUpdate) SetShowInToc(v bool) {
	o.ShowInToc = &v
}

// GetIsEmphasized returns the IsEmphasized field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetIsEmphasized() bool {
	if o == nil || IsNil(o.IsEmphasized) {
		var ret bool
		return ret
	}
	return *o.IsEmphasized
}

// GetIsEmphasizedOk returns a tuple with the IsEmphasized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetIsEmphasizedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEmphasized) {
		return nil, false
	}
	return o.IsEmphasized, true
}

// HasIsEmphasized returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasIsEmphasized() bool {
	if o != nil && !IsNil(o.IsEmphasized) {
		return true
	}

	return false
}

// SetIsEmphasized gets a reference to the given bool and assigns it to the IsEmphasized field.
func (o *ArticleGenericUpdate) SetIsEmphasized(v bool) {
	o.IsEmphasized = &v
}

// GetDisplayAuthor returns the DisplayAuthor field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetDisplayAuthor() bool {
	if o == nil || IsNil(o.DisplayAuthor) {
		var ret bool
		return ret
	}
	return *o.DisplayAuthor
}

// GetDisplayAuthorOk returns a tuple with the DisplayAuthor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetDisplayAuthorOk() (*bool, bool) {
	if o == nil || IsNil(o.DisplayAuthor) {
		return nil, false
	}
	return o.DisplayAuthor, true
}

// HasDisplayAuthor returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasDisplayAuthor() bool {
	if o != nil && !IsNil(o.DisplayAuthor) {
		return true
	}

	return false
}

// SetDisplayAuthor gets a reference to the given bool and assigns it to the DisplayAuthor field.
func (o *ArticleGenericUpdate) SetDisplayAuthor(v bool) {
	o.DisplayAuthor = &v
}

// GetDisplayChildrenUnder returns the DisplayChildrenUnder field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetDisplayChildrenUnder() bool {
	if o == nil || IsNil(o.DisplayChildrenUnder) {
		var ret bool
		return ret
	}
	return *o.DisplayChildrenUnder
}

// GetDisplayChildrenUnderOk returns a tuple with the DisplayChildrenUnder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetDisplayChildrenUnderOk() (*bool, bool) {
	if o == nil || IsNil(o.DisplayChildrenUnder) {
		return nil, false
	}
	return o.DisplayChildrenUnder, true
}

// HasDisplayChildrenUnder returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasDisplayChildrenUnder() bool {
	if o != nil && !IsNil(o.DisplayChildrenUnder) {
		return true
	}

	return false
}

// SetDisplayChildrenUnder gets a reference to the given bool and assigns it to the DisplayChildrenUnder field.
func (o *ArticleGenericUpdate) SetDisplayChildrenUnder(v bool) {
	o.DisplayChildrenUnder = &v
}

// GetDisplayTitle returns the DisplayTitle field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetDisplayTitle() bool {
	if o == nil || IsNil(o.DisplayTitle) {
		var ret bool
		return ret
	}
	return *o.DisplayTitle
}

// GetDisplayTitleOk returns a tuple with the DisplayTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetDisplayTitleOk() (*bool, bool) {
	if o == nil || IsNil(o.DisplayTitle) {
		return nil, false
	}
	return o.DisplayTitle, true
}

// HasDisplayTitle returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasDisplayTitle() bool {
	if o != nil && !IsNil(o.DisplayTitle) {
		return true
	}

	return false
}

// SetDisplayTitle gets a reference to the given bool and assigns it to the DisplayTitle field.
func (o *ArticleGenericUpdate) SetDisplayTitle(v bool) {
	o.DisplayTitle = &v
}

// GetDisplaySheet returns the DisplaySheet field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetDisplaySheet() bool {
	if o == nil || IsNil(o.DisplaySheet) {
		var ret bool
		return ret
	}
	return *o.DisplaySheet
}

// GetDisplaySheetOk returns a tuple with the DisplaySheet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetDisplaySheetOk() (*bool, bool) {
	if o == nil || IsNil(o.DisplaySheet) {
		return nil, false
	}
	return o.DisplaySheet, true
}

// HasDisplaySheet returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasDisplaySheet() bool {
	if o != nil && !IsNil(o.DisplaySheet) {
		return true
	}

	return false
}

// SetDisplaySheet gets a reference to the given bool and assigns it to the DisplaySheet field.
func (o *ArticleGenericUpdate) SetDisplaySheet(v bool) {
	o.DisplaySheet = &v
}

// GetBadge returns the Badge field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ArticleGenericUpdate) GetBadge() string {
	if o == nil || IsNil(o.Badge.Get()) {
		var ret string
		return ret
	}
	return *o.Badge.Get()
}

// GetBadgeOk returns a tuple with the Badge field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ArticleGenericUpdate) GetBadgeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Badge.Get(), o.Badge.IsSet()
}

// HasBadge returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasBadge() bool {
	if o != nil && o.Badge.IsSet() {
		return true
	}

	return false
}

// SetBadge gets a reference to the given NullableString and assigns it to the Badge field.
func (o *ArticleGenericUpdate) SetBadge(v string) {
	o.Badge.Set(&v)
}
// SetBadgeNil sets the value for Badge to be an explicit nil
func (o *ArticleGenericUpdate) SetBadgeNil() {
	o.Badge.Set(nil)
}

// UnsetBadge ensures that no value is present for Badge, not even an explicit nil
func (o *ArticleGenericUpdate) UnsetBadge() {
	o.Badge.Unset()
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetSecrets() []Object {
	if o == nil || IsNil(o.Secrets) {
		var ret []Object
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetSecretsOk() ([]Object, bool) {
	if o == nil || IsNil(o.Secrets) {
		return nil, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given []Object and assigns it to the Secrets field.
func (o *ArticleGenericUpdate) SetSecrets(v []Object) {
	o.Secrets = v
}

// GetHistories returns the Histories field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetHistories() []Object {
	if o == nil || IsNil(o.Histories) {
		var ret []Object
		return ret
	}
	return o.Histories
}

// GetHistoriesOk returns a tuple with the Histories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetHistoriesOk() ([]Object, bool) {
	if o == nil || IsNil(o.Histories) {
		return nil, false
	}
	return o.Histories, true
}

// HasHistories returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasHistories() bool {
	if o != nil && !IsNil(o.Histories) {
		return true
	}

	return false
}

// SetHistories gets a reference to the given []Object and assigns it to the Histories field.
func (o *ArticleGenericUpdate) SetHistories(v []Object) {
	o.Histories = v
}

// GetEditURL returns the EditURL field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetEditURL() string {
	if o == nil || IsNil(o.EditURL) {
		var ret string
		return ret
	}
	return *o.EditURL
}

// GetEditURLOk returns a tuple with the EditURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetEditURLOk() (*string, bool) {
	if o == nil || IsNil(o.EditURL) {
		return nil, false
	}
	return o.EditURL, true
}

// HasEditURL returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasEditURL() bool {
	if o != nil && !IsNil(o.EditURL) {
		return true
	}

	return false
}

// SetEditURL gets a reference to the given string and assigns it to the EditURL field.
func (o *ArticleGenericUpdate) SetEditURL(v string) {
	o.EditURL = &v
}

// GetManuscripts returns the Manuscripts field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetManuscripts() []ArticleGenericUpdateObjectPropertiesManuscriptsInner {
	if o == nil || IsNil(o.Manuscripts) {
		var ret []ArticleGenericUpdateObjectPropertiesManuscriptsInner
		return ret
	}
	return o.Manuscripts
}

// GetManuscriptsOk returns a tuple with the Manuscripts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetManuscriptsOk() ([]ArticleGenericUpdateObjectPropertiesManuscriptsInner, bool) {
	if o == nil || IsNil(o.Manuscripts) {
		return nil, false
	}
	return o.Manuscripts, true
}

// HasManuscripts returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasManuscripts() bool {
	if o != nil && !IsNil(o.Manuscripts) {
		return true
	}

	return false
}

// SetManuscripts gets a reference to the given []ArticleGenericUpdateObjectPropertiesManuscriptsInner and assigns it to the Manuscripts field.
func (o *ArticleGenericUpdate) SetManuscripts(v []ArticleGenericUpdateObjectPropertiesManuscriptsInner) {
	o.Manuscripts = v
}

// GetBlock returns the Block field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetBlock() ArticleGenericUpdateObjectPropertiesBlock {
	if o == nil || IsNil(o.Block) {
		var ret ArticleGenericUpdateObjectPropertiesBlock
		return ret
	}
	return *o.Block
}

// GetBlockOk returns a tuple with the Block field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetBlockOk() (*ArticleGenericUpdateObjectPropertiesBlock, bool) {
	if o == nil || IsNil(o.Block) {
		return nil, false
	}
	return o.Block, true
}

// HasBlock returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasBlock() bool {
	if o != nil && !IsNil(o.Block) {
		return true
	}

	return false
}

// SetBlock gets a reference to the given ArticleGenericUpdateObjectPropertiesBlock and assigns it to the Block field.
func (o *ArticleGenericUpdate) SetBlock(v ArticleGenericUpdateObjectPropertiesBlock) {
	o.Block = &v
}

// GetArticleParent returns the ArticleParent field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetArticleParent() ArticleGenericUpdateObjectPropertiesManuscriptsInner {
	if o == nil || IsNil(o.ArticleParent) {
		var ret ArticleGenericUpdateObjectPropertiesManuscriptsInner
		return ret
	}
	return *o.ArticleParent
}

// GetArticleParentOk returns a tuple with the ArticleParent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetArticleParentOk() (*ArticleGenericUpdateObjectPropertiesManuscriptsInner, bool) {
	if o == nil || IsNil(o.ArticleParent) {
		return nil, false
	}
	return o.ArticleParent, true
}

// HasArticleParent returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasArticleParent() bool {
	if o != nil && !IsNil(o.ArticleParent) {
		return true
	}

	return false
}

// SetArticleParent gets a reference to the given ArticleGenericUpdateObjectPropertiesManuscriptsInner and assigns it to the ArticleParent field.
func (o *ArticleGenericUpdate) SetArticleParent(v ArticleGenericUpdateObjectPropertiesManuscriptsInner) {
	o.ArticleParent = &v
}

// GetGallery returns the Gallery field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetGallery() ArticleGenericUpdateObjectPropertiesBlock {
	if o == nil || IsNil(o.Gallery) {
		var ret ArticleGenericUpdateObjectPropertiesBlock
		return ret
	}
	return *o.Gallery
}

// GetGalleryOk returns a tuple with the Gallery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetGalleryOk() (*ArticleGenericUpdateObjectPropertiesBlock, bool) {
	if o == nil || IsNil(o.Gallery) {
		return nil, false
	}
	return o.Gallery, true
}

// HasGallery returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasGallery() bool {
	if o != nil && !IsNil(o.Gallery) {
		return true
	}

	return false
}

// SetGallery gets a reference to the given ArticleGenericUpdateObjectPropertiesBlock and assigns it to the Gallery field.
func (o *ArticleGenericUpdate) SetGallery(v ArticleGenericUpdateObjectPropertiesBlock) {
	o.Gallery = &v
}

// GetArticlePrevious returns the ArticlePrevious field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetArticlePrevious() ArticleGenericUpdateObjectPropertiesManuscriptsInner {
	if o == nil || IsNil(o.ArticlePrevious) {
		var ret ArticleGenericUpdateObjectPropertiesManuscriptsInner
		return ret
	}
	return *o.ArticlePrevious
}

// GetArticlePreviousOk returns a tuple with the ArticlePrevious field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetArticlePreviousOk() (*ArticleGenericUpdateObjectPropertiesManuscriptsInner, bool) {
	if o == nil || IsNil(o.ArticlePrevious) {
		return nil, false
	}
	return o.ArticlePrevious, true
}

// HasArticlePrevious returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasArticlePrevious() bool {
	if o != nil && !IsNil(o.ArticlePrevious) {
		return true
	}

	return false
}

// SetArticlePrevious gets a reference to the given ArticleGenericUpdateObjectPropertiesManuscriptsInner and assigns it to the ArticlePrevious field.
func (o *ArticleGenericUpdate) SetArticlePrevious(v ArticleGenericUpdateObjectPropertiesManuscriptsInner) {
	o.ArticlePrevious = &v
}

// GetArticleNext returns the ArticleNext field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetArticleNext() ArticleGenericUpdateObjectPropertiesManuscriptsInner {
	if o == nil || IsNil(o.ArticleNext) {
		var ret ArticleGenericUpdateObjectPropertiesManuscriptsInner
		return ret
	}
	return *o.ArticleNext
}

// GetArticleNextOk returns a tuple with the ArticleNext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetArticleNextOk() (*ArticleGenericUpdateObjectPropertiesManuscriptsInner, bool) {
	if o == nil || IsNil(o.ArticleNext) {
		return nil, false
	}
	return o.ArticleNext, true
}

// HasArticleNext returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasArticleNext() bool {
	if o != nil && !IsNil(o.ArticleNext) {
		return true
	}

	return false
}

// SetArticleNext gets a reference to the given ArticleGenericUpdateObjectPropertiesManuscriptsInner and assigns it to the ArticleNext field.
func (o *ArticleGenericUpdate) SetArticleNext(v ArticleGenericUpdateObjectPropertiesManuscriptsInner) {
	o.ArticleNext = &v
}

// GetCover returns the Cover field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetCover() ArticleGenericUpdateObjectPropertiesBlock {
	if o == nil || IsNil(o.Cover) {
		var ret ArticleGenericUpdateObjectPropertiesBlock
		return ret
	}
	return *o.Cover
}

// GetCoverOk returns a tuple with the Cover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetCoverOk() (*ArticleGenericUpdateObjectPropertiesBlock, bool) {
	if o == nil || IsNil(o.Cover) {
		return nil, false
	}
	return o.Cover, true
}

// HasCover returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasCover() bool {
	if o != nil && !IsNil(o.Cover) {
		return true
	}

	return false
}

// SetCover gets a reference to the given ArticleGenericUpdateObjectPropertiesBlock and assigns it to the Cover field.
func (o *ArticleGenericUpdate) SetCover(v ArticleGenericUpdateObjectPropertiesBlock) {
	o.Cover = &v
}

// GetWorld returns the World field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetWorld() ArticleGenericUpdateObjectPropertiesManuscriptsInner {
	if o == nil || IsNil(o.World) {
		var ret ArticleGenericUpdateObjectPropertiesManuscriptsInner
		return ret
	}
	return *o.World
}

// GetWorldOk returns a tuple with the World field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetWorldOk() (*ArticleGenericUpdateObjectPropertiesManuscriptsInner, bool) {
	if o == nil || IsNil(o.World) {
		return nil, false
	}
	return o.World, true
}

// HasWorld returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasWorld() bool {
	if o != nil && !IsNil(o.World) {
		return true
	}

	return false
}

// SetWorld gets a reference to the given ArticleGenericUpdateObjectPropertiesManuscriptsInner and assigns it to the World field.
func (o *ArticleGenericUpdate) SetWorld(v ArticleGenericUpdateObjectPropertiesManuscriptsInner) {
	o.World = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetCategory() ArticleGenericUpdateObjectPropertiesManuscriptsInner {
	if o == nil || IsNil(o.Category) {
		var ret ArticleGenericUpdateObjectPropertiesManuscriptsInner
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetCategoryOk() (*ArticleGenericUpdateObjectPropertiesManuscriptsInner, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given ArticleGenericUpdateObjectPropertiesManuscriptsInner and assigns it to the Category field.
func (o *ArticleGenericUpdate) SetCategory(v ArticleGenericUpdateObjectPropertiesManuscriptsInner) {
	o.Category = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetAuthor() ArticleGenericUpdateObjectPropertiesManuscriptsInner {
	if o == nil || IsNil(o.Author) {
		var ret ArticleGenericUpdateObjectPropertiesManuscriptsInner
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetAuthorOk() (*ArticleGenericUpdateObjectPropertiesManuscriptsInner, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given ArticleGenericUpdateObjectPropertiesManuscriptsInner and assigns it to the Author field.
func (o *ArticleGenericUpdate) SetAuthor(v ArticleGenericUpdateObjectPropertiesManuscriptsInner) {
	o.Author = &v
}

// GetSubscribergroups returns the Subscribergroups field value if set, zero value otherwise.
func (o *ArticleGenericUpdate) GetSubscribergroups() []ArticleGenericUpdateObjectPropertiesManuscriptsInner {
	if o == nil || IsNil(o.Subscribergroups) {
		var ret []ArticleGenericUpdateObjectPropertiesManuscriptsInner
		return ret
	}
	return o.Subscribergroups
}

// GetSubscribergroupsOk returns a tuple with the Subscribergroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleGenericUpdate) GetSubscribergroupsOk() ([]ArticleGenericUpdateObjectPropertiesManuscriptsInner, bool) {
	if o == nil || IsNil(o.Subscribergroups) {
		return nil, false
	}
	return o.Subscribergroups, true
}

// HasSubscribergroups returns a boolean if a field has been set.
func (o *ArticleGenericUpdate) HasSubscribergroups() bool {
	if o != nil && !IsNil(o.Subscribergroups) {
		return true
	}

	return false
}

// SetSubscribergroups gets a reference to the given []ArticleGenericUpdateObjectPropertiesManuscriptsInner and assigns it to the Subscribergroups field.
func (o *ArticleGenericUpdate) SetSubscribergroups(v []ArticleGenericUpdateObjectPropertiesManuscriptsInner) {
	o.Subscribergroups = v
}

func (o ArticleGenericUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArticleGenericUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.IsWip) {
		toSerialize["isWip"] = o.IsWip
	}
	if !IsNil(o.IsDraft) {
		toSerialize["isDraft"] = o.IsDraft
	}
	if !IsNil(o.EntityClass) {
		toSerialize["entityClass"] = o.EntityClass
	}
	if o.Icon.IsSet() {
		toSerialize["icon"] = o.Icon.Get()
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.FolderId) {
		toSerialize["folderId"] = o.FolderId
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.UpdateDate) {
		toSerialize["updateDate"] = o.UpdateDate
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Excerpt) {
		toSerialize["excerpt"] = o.Excerpt
	}
	if !IsNil(o.Wordcount) {
		toSerialize["wordcount"] = o.Wordcount
	}
	if !IsNil(o.CreationDate) {
		toSerialize["creationDate"] = o.CreationDate
	}
	if !IsNil(o.PublicationDate) {
		toSerialize["publicationDate"] = o.PublicationDate
	}
	if !IsNil(o.NotificationDate) {
		toSerialize["notificationDate"] = o.NotificationDate
	}
	if !IsNil(o.Likes) {
		toSerialize["likes"] = o.Likes
	}
	if !IsNil(o.Views) {
		toSerialize["views"] = o.Views
	}
	if o.UserMetadata != nil {
		toSerialize["userMetadata"] = o.UserMetadata
	}
	if o.ArticleMetadata != nil {
		toSerialize["articleMetadata"] = o.ArticleMetadata
	}
	if !IsNil(o.CssClasses) {
		toSerialize["cssClasses"] = o.CssClasses
	}
	if !IsNil(o.DisplayCss) {
		toSerialize["displayCss"] = o.DisplayCss
	}
	if !IsNil(o.TemplateType) {
		toSerialize["templateType"] = o.TemplateType
	}
	if o.CustomArticleTemplate.IsSet() {
		toSerialize["customArticleTemplate"] = o.CustomArticleTemplate.Get()
	}
	if !IsNil(o.Pronunciation) {
		toSerialize["pronunciation"] = o.Pronunciation
	}
	if !IsNil(o.Snippet) {
		toSerialize["snippet"] = o.Snippet
	}
	if !IsNil(o.Seeded) {
		toSerialize["seeded"] = o.Seeded
	}
	if !IsNil(o.Sidebarcontent) {
		toSerialize["sidebarcontent"] = o.Sidebarcontent
	}
	if !IsNil(o.Sidepanelcontenttop) {
		toSerialize["sidepanelcontenttop"] = o.Sidepanelcontenttop
	}
	if !IsNil(o.Sidepanelcontent) {
		toSerialize["sidepanelcontent"] = o.Sidepanelcontent
	}
	if !IsNil(o.Sidebarcontentbottom) {
		toSerialize["sidebarcontentbottom"] = o.Sidebarcontentbottom
	}
	if !IsNil(o.Footnotes) {
		toSerialize["footnotes"] = o.Footnotes
	}
	if !IsNil(o.Fullfooter) {
		toSerialize["fullfooter"] = o.Fullfooter
	}
	if !IsNil(o.Authornotes) {
		toSerialize["authornotes"] = o.Authornotes
	}
	if !IsNil(o.Scrapbook) {
		toSerialize["scrapbook"] = o.Scrapbook
	}
	if !IsNil(o.Credits) {
		toSerialize["credits"] = o.Credits
	}
	if !IsNil(o.DisplaySidebar) {
		toSerialize["displaySidebar"] = o.DisplaySidebar
	}
	if !IsNil(o.Timeline) {
		toSerialize["timeline"] = o.Timeline
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.ShowSeeded) {
		toSerialize["showSeeded"] = o.ShowSeeded
	}
	if !IsNil(o.WebhookUpdate) {
		toSerialize["webhookUpdate"] = o.WebhookUpdate
	}
	if !IsNil(o.CommunityUpdate) {
		toSerialize["communityUpdate"] = o.CommunityUpdate
	}
	if o.CommentPlaceholder.IsSet() {
		toSerialize["commentPlaceholder"] = o.CommentPlaceholder.Get()
	}
	if o.MetaTitle.IsSet() {
		toSerialize["metaTitle"] = o.MetaTitle.Get()
	}
	if o.MetadDescription.IsSet() {
		toSerialize["metadDescription"] = o.MetadDescription.Get()
	}
	if o.Subheading.IsSet() {
		toSerialize["subheading"] = o.Subheading.Get()
	}
	if !IsNil(o.CoverIsMap) {
		toSerialize["coverIsMap"] = o.CoverIsMap
	}
	if !IsNil(o.IsFeaturedArticle) {
		toSerialize["isFeaturedArticle"] = o.IsFeaturedArticle
	}
	if !IsNil(o.IsAdultContent) {
		toSerialize["isAdultContent"] = o.IsAdultContent
	}
	if !IsNil(o.IsLocked) {
		toSerialize["isLocked"] = o.IsLocked
	}
	if !IsNil(o.AllowComments) {
		toSerialize["allowComments"] = o.AllowComments
	}
	if !IsNil(o.ShowInToc) {
		toSerialize["showInToc"] = o.ShowInToc
	}
	if !IsNil(o.IsEmphasized) {
		toSerialize["isEmphasized"] = o.IsEmphasized
	}
	if !IsNil(o.DisplayAuthor) {
		toSerialize["displayAuthor"] = o.DisplayAuthor
	}
	if !IsNil(o.DisplayChildrenUnder) {
		toSerialize["displayChildrenUnder"] = o.DisplayChildrenUnder
	}
	if !IsNil(o.DisplayTitle) {
		toSerialize["displayTitle"] = o.DisplayTitle
	}
	if !IsNil(o.DisplaySheet) {
		toSerialize["displaySheet"] = o.DisplaySheet
	}
	if o.Badge.IsSet() {
		toSerialize["badge"] = o.Badge.Get()
	}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	if !IsNil(o.Histories) {
		toSerialize["histories"] = o.Histories
	}
	if !IsNil(o.EditURL) {
		toSerialize["editURL"] = o.EditURL
	}
	if !IsNil(o.Manuscripts) {
		toSerialize["manuscripts"] = o.Manuscripts
	}
	if !IsNil(o.Block) {
		toSerialize["block"] = o.Block
	}
	if !IsNil(o.ArticleParent) {
		toSerialize["articleParent"] = o.ArticleParent
	}
	if !IsNil(o.Gallery) {
		toSerialize["gallery"] = o.Gallery
	}
	if !IsNil(o.ArticlePrevious) {
		toSerialize["articlePrevious"] = o.ArticlePrevious
	}
	if !IsNil(o.ArticleNext) {
		toSerialize["articleNext"] = o.ArticleNext
	}
	if !IsNil(o.Cover) {
		toSerialize["cover"] = o.Cover
	}
	if !IsNil(o.World) {
		toSerialize["world"] = o.World
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Subscribergroups) {
		toSerialize["subscribergroups"] = o.Subscribergroups
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ArticleGenericUpdate) UnmarshalJSON(data []byte) (err error) {
	varArticleGenericUpdate := _ArticleGenericUpdate{}

	err = json.Unmarshal(data, &varArticleGenericUpdate)

	if err != nil {
		return err
	}

	*o = ArticleGenericUpdate(varArticleGenericUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "title")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "state")
		delete(additionalProperties, "isWip")
		delete(additionalProperties, "isDraft")
		delete(additionalProperties, "entityClass")
		delete(additionalProperties, "icon")
		delete(additionalProperties, "url")
		delete(additionalProperties, "folderId")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "updateDate")
		delete(additionalProperties, "position")
		delete(additionalProperties, "excerpt")
		delete(additionalProperties, "wordcount")
		delete(additionalProperties, "creationDate")
		delete(additionalProperties, "publicationDate")
		delete(additionalProperties, "notificationDate")
		delete(additionalProperties, "likes")
		delete(additionalProperties, "views")
		delete(additionalProperties, "userMetadata")
		delete(additionalProperties, "articleMetadata")
		delete(additionalProperties, "cssClasses")
		delete(additionalProperties, "displayCss")
		delete(additionalProperties, "templateType")
		delete(additionalProperties, "customArticleTemplate")
		delete(additionalProperties, "pronunciation")
		delete(additionalProperties, "snippet")
		delete(additionalProperties, "seeded")
		delete(additionalProperties, "sidebarcontent")
		delete(additionalProperties, "sidepanelcontenttop")
		delete(additionalProperties, "sidepanelcontent")
		delete(additionalProperties, "sidebarcontentbottom")
		delete(additionalProperties, "footnotes")
		delete(additionalProperties, "fullfooter")
		delete(additionalProperties, "authornotes")
		delete(additionalProperties, "scrapbook")
		delete(additionalProperties, "credits")
		delete(additionalProperties, "displaySidebar")
		delete(additionalProperties, "timeline")
		delete(additionalProperties, "prompt")
		delete(additionalProperties, "showSeeded")
		delete(additionalProperties, "webhookUpdate")
		delete(additionalProperties, "communityUpdate")
		delete(additionalProperties, "commentPlaceholder")
		delete(additionalProperties, "metaTitle")
		delete(additionalProperties, "metadDescription")
		delete(additionalProperties, "subheading")
		delete(additionalProperties, "coverIsMap")
		delete(additionalProperties, "isFeaturedArticle")
		delete(additionalProperties, "isAdultContent")
		delete(additionalProperties, "isLocked")
		delete(additionalProperties, "allowComments")
		delete(additionalProperties, "showInToc")
		delete(additionalProperties, "isEmphasized")
		delete(additionalProperties, "displayAuthor")
		delete(additionalProperties, "displayChildrenUnder")
		delete(additionalProperties, "displayTitle")
		delete(additionalProperties, "displaySheet")
		delete(additionalProperties, "badge")
		delete(additionalProperties, "secrets")
		delete(additionalProperties, "histories")
		delete(additionalProperties, "editURL")
		delete(additionalProperties, "manuscripts")
		delete(additionalProperties, "block")
		delete(additionalProperties, "articleParent")
		delete(additionalProperties, "gallery")
		delete(additionalProperties, "articlePrevious")
		delete(additionalProperties, "articleNext")
		delete(additionalProperties, "cover")
		delete(additionalProperties, "world")
		delete(additionalProperties, "category")
		delete(additionalProperties, "author")
		delete(additionalProperties, "subscribergroups")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableArticleGenericUpdate struct {
	value *ArticleGenericUpdate
	isSet bool
}

func (v NullableArticleGenericUpdate) Get() *ArticleGenericUpdate {
	return v.value
}

func (v *NullableArticleGenericUpdate) Set(val *ArticleGenericUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleGenericUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleGenericUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleGenericUpdate(val *ArticleGenericUpdate) *NullableArticleGenericUpdate {
	return &NullableArticleGenericUpdate{value: val, isSet: true}
}

func (v NullableArticleGenericUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleGenericUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


